-- Import de igrejas — REGIONAL 005 (49 igrejas, o maior grupo
-- regional). Mesmo padrão das migrations 079/081-085.
INSERT INTO public.units (type, name, parent_id, is_headquarters, is_sector_mother, status)
SELECT 'IGREJA', v.nome, (SELECT id FROM public.units WHERE type='SETOR' AND name='REGIONAL 005'), false, v.lider, 'ACTIVE'
FROM (VALUES
  ('PAU DA LIMA/BA', true),('BTN 2/BA', false),('CALABETÃO/BA', false),('COCISA/BA', false),
  ('CONCORDIA/BA', false),('CONSTITUINTE/BA', false),('FAZENDA CANOAS/BA', false),('FAZENDA COUTOS/BA', false),
  ('FAZENDA GRANDE 4/BA', false),('FAZENDA URUPI/BA', false),('GENARO/BA', false),('GLEBA H/BA', false),
  ('HUMILDES/BA', false),('IMBASSAY/BA', false),('JACUMIRIM/BA', false),('MARECHAL RONDON/BA', false),
  ('MOURA BASTOS/BA', false),('MUCAMBO/BA', false),('NOVA SOURE/BA', false),('PITUAÇU/BA', false),
  ('RETIRO/BA', false),('RIO REAL/BA', false),('RIO SENA/BA', false),('SANTA BRIGIDA/BA', false),
  ('SANTA HELENA/BA', false),('SAPEAÇU/BA', false),('SITIO DO TARÁ/BA', false),
  ('SUB - ALTO DO CABRITO/BA', false),('SUB - BETA 4/BA', false),('SUB - CALABETÃO 02/BA', false),
  ('SUB - CEASA 2/BA', false),('SUB - JARDIM CAJAZEIRAS', false),('SUB - JATOBÁ/PE', false),
  ('SUB - LIMOEIRO/BA', false),('SUB - LOBATO/BA', false),('SUB - MARECHAL RONDON 02/BA', false),
  ('SUB - MARECHAL RONDON 03/BA', false),('SUB - NOVA SOURE 02/BA', false),('SUB - OLHOS DÁGUA/BA', false),
  ('SUB - PARQUE VERDE/BA', false),('SUB - PERIPERI/BA', false),('SUB - PHOC 03/BA', false),
  ('SUB - POVOADO DO GARRANCHIO/BA', false),('SUB - POVOADO DO RASO/BA', false),
  ('SUB - RECANTO DA URBIS/BA', false),('SUB - TABULEIRINHO/BA', false),('SUB - TERRA NOVA/BA', false),
  ('TRÊS LAGOAS/BA', false),('URBIS/BA', false)
) AS v(nome, lider);

INSERT INTO public.churches (name, pastor_name, pastor_phone, member_count, address, city, state, zip_code, unit_id, is_sector_head, status)
SELECT c.nome, c.dirigente, c.celular, c.membros, c.endereco, c.cidade, c.uf, c.cep,
  (SELECT id FROM public.units WHERE type='IGREJA' AND name=c.nome AND parent_id=(SELECT id FROM public.units WHERE type='SETOR' AND name='REGIONAL 005')),
  c.lider, 'ACTIVE'
FROM (VALUES
  ('PAU DA LIMA/BA','ADENILSON EVANGELISTA DE ARAÚJO','(81) 99595-3795',212,'Rua Jayme Vieira Lima, 191 - Pau da Lima','Salvador','BA','41235-000',true),
  ('BTN 2/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,73,'Rua Padre Lourenço, 2060 - PQ. NOSSA SENHORA DAS GRAÇAS','Paulo Afonso','BA','48600-000',false),
  ('CALABETÃO/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,44,'Rua Do Campo, 71 - CALABETAO','Salvador','BA','41227-000',false),
  ('COCISA/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,17,'RUA TELMA CRISTINA, 5 - PARIPE COCISA','Salvador','BA','40810-550',false),
  ('CONCORDIA/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,18,'RUA QUADRA, 157 - CONCORDIA','Concórdia','SC','42850-000',false),
  ('CONSTITUINTE/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,19,'RUA ANA CRISTINA, 49 - NOVA CONSTITUINTE','Salvador','BA','40720-188',false),
  ('FAZENDA CANOAS/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,67,'FAZENDA CANOAS, S/ Nº - Oliveira dos Campinhos','Santo Amaro','BA','44200-000',false),
  ('FAZENDA COUTOS/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,71,'Rua Eixo, Quadra 38, nº 22F - FAZ. COUTOS III','Salvador','BA','40731-615',false),
  ('FAZENDA GRANDE 4/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,33,'RUA SILVA, s/nº - FAZENDA GRANDE 4','Salvador','BA','42340-310',false),
  ('FAZENDA URUPI/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,11,'AVENIDA DO ROQUE, S/ Nº - Oliveira dos Campinhos','Santo Amaro','BA','44200-000',false),
  ('GENARO/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,36,'RUA ALMIRANTE SALDANHA, 247 - PQ. PETROPOLIS','Piracicaba','SP','42850-000',false),
  ('GLEBA H/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,28,'AV. OTAVIO MANGABEIRA, 5 - SANTA MARIA','Camaçari','BA','42807-902',false),
  ('HUMILDES/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,23,'RUA TELES, 6 - DIST. HUMILDES','Feira de Santana','BA','44135-000',false),
  ('IMBASSAY/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,28,'TRAVESSA SÃO MAURÍCIO, S/Nº','Piracicaba','SP','42850-000',false),
  ('JACUMIRIM/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,20,'RUA CHICO MENDES, S/Nº - JACUMIRIM','Umirim','CE','42850-000',false),
  ('MARECHAL RONDON/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,140,'RUA PATATIVA, 179 - Marechal Rondon','Salvador','BA','41285-060',false),
  ('MOURA BASTOS/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,28,'RUA PROF. LUIS MOURA BASTOS, S/Nº - Moura Bastos','Bastos','SP','41227-135',false),
  ('MUCAMBO/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,13,'RUA DO MUCAMBO - CENTRO','Rio Real','BA','48330-000',false),
  ('NOVA SOURE/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,70,'Rua Asa Branca, 212 - Fatima','Nova Soure','BA','48460-000',false),
  ('PITUAÇU/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,27,'Rua Bananal Nº46E, 46-E','Salvador','BA','41741-480',false),
  ('RETIRO/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,87,'Rua Mello Moraes Filho, 389 - acima do antigo banco Bradesco','Salvador','BA','40350-000',false),
  ('RIO REAL/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,50,'RUA Irmã Dulce, 89 - CENTRO','Rio Real','BA','48330-000',false),
  ('RIO SENA/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,48,'Rua Ambrosina Arruda, 313E - Rio Sena','Salvador','BA','41715-364',false),
  ('SANTA BRIGIDA/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,34,'Av. Rui Barbosa, S/N - SANTA BRIGIDA','Santa Brígida','BA','48570-000',false),
  ('SANTA HELENA/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,13,'Av. Raul Seixas, 2073 - Santa Helena','Santa Helena','MA','42850-000',false),
  ('SAPEAÇU/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,0,'Rua da Vitória, 629 - CENTRO','Açu','RN','44530-000',false),
  ('SITIO DO TARÁ/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,24,'SITIO DO TARÁ, S/N - PQ. NOSSA SENHORA DAS GRAÇAS','Paulo Afonso','BA','48600-000',false),
  ('SUB - ALTO DO CABRITO/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,31,'Rua Doutor Jairo Carneiro de Araujo, 378 - ALTO DO CABRITO','Salvador','BA','40484-670',false),
  ('SUB - BETA 4/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,13,'RUA LOTEAMENTO JOÃO DO LEITE BETA 4, S/N - ENTRONCAMENTO','Piracicaba','SP','42850-000',false),
  ('SUB - CALABETÃO 02/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,0,'Rua das Pedreiras, 27 - CALABETAO','Salvador','BA','41227-260',false),
  ('SUB - CEASA 2/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,1,'2º TRAVESSA 2 DE JULHO DA CEASA, 0 - CEASA','Salvador','BA','41404-075',false),
  ('SUB - JARDIM CAJAZEIRAS','ADENILSON EVANGELISTA DE ARAÚJO',NULL,25,'Rua Pastor Rodrigo Santana, 145 - Pau da Lima','Salvador','BA','41247-060',false),
  ('SUB - JATOBÁ/PE','ADENILSON EVANGELISTA DE ARAÚJO',NULL,2,'AVENIDA RECIFE, 1 - CENTRO','Jatobá','PE','56470-000',false),
  ('SUB - LIMOEIRO/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,5,'RUA MADRE DE DEUS, 1188 - LIMOEIRO','Feira de Santana','BA','44055-770',false),
  ('SUB - LOBATO/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,1,'Rua Três Amigos do Lobato, 44 - Lobato','Salvador','BA','40471-115',false),
  ('SUB - MARECHAL RONDON 02/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,14,'Rua São José, 186 - Marechal Rondon','Salvador','BA','41281-050',false),
  ('SUB - MARECHAL RONDON 03/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,10,'Rua Deusdete Muniz, 37 - Marechal Rondon','Salvador','BA','41280-020',false),
  ('SUB - NOVA SOURE 02/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,0,'RUA MANOEL FERREIRA DA SILVA S/N - Fatima','Nova Soure','BA','48460-000',false),
  ('SUB - OLHOS DÁGUA/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,5,'RUA OLHOS DAGUA - CENTRO','Rio Real','BA','48330-000',false),
  ('SUB - PARQUE VERDE/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,15,'RUA LAURO DE FREITAS, 313 - PARQUE VERDE','Camaçari','BA','42810-626',false),
  ('SUB - PERIPERI/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,9,'Rua Everaldo Cardoso, 39 - NOVA CONSTITUINTE','Salvador','BA','40720-282',false),
  ('SUB - PHOC 03/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,0,'Avenida Acajutiba - Acajutiba','Camaçari','BA','42805-350',false),
  ('SUB - POVOADO DO GARRANCHIO/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,2,'DISTRITO NOVA SOURE - NOVA SOURE/BA','Salvador','BA','48460-000',false),
  ('SUB - POVOADO DO RASO/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,2,'DISTRITO DE NOVA SOURE - NOVA SOURE/BA','Salvador','BA','48460-000',false),
  ('SUB - RECANTO DA URBIS/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,15,'RUA RECANTO DA URBIS, 0 - Periperi','Salvador','BA','40720-090',false),
  ('SUB - TABULEIRINHO/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,0,'POVOADO SÍTIO DO TARÁ, S/ Nº - ZONA RURAL','Paulo Afonso','BA','48609-156',false),
  ('SUB - TERRA NOVA/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,28,'RUA MARIA QUITÉRIA, 259 - CENTRO','Terra Nova','BA','44270-000',false),
  ('TRÊS LAGOAS/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,21,'Rua Manoel José da Silva, 75a, 75 - CENTRO','Paulo Afonso','BA','48600-000',false),
  ('URBIS/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,82,'RUA DIRETA DA IRLANDA, 177 - Urbis','URBIS','BA','42850-000',false)
) AS c(nome, dirigente, celular, membros, endereco, cidade, uf, cep, lider);
