-- Import de igrejas — REGIONAL 010, 012, 013.
-- Conteúdo gerado a partir dos dados já aplicados em produção
-- (conferido via SELECT direto no banco), mesmo padrão units→churches.

INSERT INTO public.units (type, name, parent_id, is_headquarters, is_sector_mother, status)
SELECT 'IGREJA', v.nome, (SELECT id FROM public.units WHERE type='SETOR' AND name=v.grupo), false, v.lider, 'ACTIVE'
FROM (VALUES
  ('REGIONAL 010','SANTO ÂNGELO/RS',true),('REGIONAL 010','CAIBATE / RS',false),
  ('REGIONAL 010','CARAZINHO/RS',false),('REGIONAL 010','CASCA/RS',false),
  ('REGIONAL 010','CERRO LARGO / RS',false),('REGIONAL 010','CHAPADA/RS',false),
  ('REGIONAL 010','FLORESTA/RS',false),('REGIONAL 010','GIRUÁ/RS',false),
  ('REGIONAL 010','HIPICA/RS',false),('REGIONAL 010','MARAU/RS',false),
  ('REGIONAL 010','NOVO BARREIRO/RS',false),('REGIONAL 010','ORIENTAL',false),
  ('REGIONAL 010','PASSO FUNDO/RS',false),('REGIONAL 010','PINHEIRO MARCADO',false),
  ('REGIONAL 010','ROGOSWSKI / RS',false),('REGIONAL 010','SÃO LUIZ GONZAGA',false),
  ('REGIONAL 010','SÃO LUIZ GONZAGA / RS',false),('REGIONAL 010','SUB - NAO ME TOQUE/RS',false),
  ('REGIONAL 010','TAPEJARA/RS',false),('REGIONAL 010','VILA MARIA / RS',false),
  ('REGIONAL 012','CURITIBA/PR',true),('REGIONAL 012','SITIO CERCADO - NOVO HORIZONTE',false),
  ('REGIONAL 012','SITIO CERCADO OSTERNACK',false),
  ('REGIONAL 013','CARUARU/PE',true),('REGIONAL 013','CACHOEIRINHA / PE CENTRO',false),
  ('REGIONAL 013','CACHOEIRINHA / PE NOÉMIA',false),('REGIONAL 013','JOSE CARLOS DE OLIVEIRA/PE',false),
  ('REGIONAL 013','JOSÉ LIBERATO/PE',false),('REGIONAL 013','PESQUEIRA CENTENARIO/PE',false),
  ('REGIONAL 013','SANHARÓ/PE',false),('REGIONAL 013','SÃO FRANCISCO - CARUARU',false),
  ('REGIONAL 013','SÃO JOÃO DA ESCÓCIA/PE',false),('REGIONAL 013','SUB - PETROPOLIS',false),
  ('REGIONAL 013','SUB - VILA DO AEROPORTO/PE',false),('REGIONAL 013','SUB - VILA IGREJINHA',false),
  ('REGIONAL 013','SUB - VILA PELADAS',false),('REGIONAL 013','SUB- RIACHO DOCE',false)
) AS v(grupo, nome, lider);

INSERT INTO public.churches (name, pastor_name, pastor_phone, member_count, address, city, state, zip_code, unit_id, is_sector_head, status)
SELECT c.nome, c.dirigente, c.celular, c.membros, c.endereco, c.cidade, c.uf, c.cep,
  (SELECT id FROM public.units WHERE type='IGREJA' AND name=c.nome AND parent_id=(SELECT id FROM public.units WHERE type='SETOR' AND name=c.grupo)),
  c.lider, 'ACTIVE'
FROM (VALUES
  ('REGIONAL 010','SANTO ÂNGELO/RS','PETERSON DONIZETE GOMES DA SILVA','(54) 99698-5589',100,'Rua Marechal Floriano, 141 - Jardim das Palmeiras','Santo Ângelo','RS','98804-340',true),
  ('REGIONAL 010','CAIBATE / RS','PETERSON DONIZETE GOMES DA SILVA',NULL,0,'ESTRADA SAÍDA VISTA ALEGRE, - VISTA ALEGRE','Caibaté','RS','97930-000',false),
  ('REGIONAL 010','CARAZINHO/RS','PETERSON DONIZETE GOMES DA SILVA',NULL,60,'Rua Arthur Bernardes, 215 - Sassi','Carazinho','RS','99500-000',false),
  ('REGIONAL 010','CASCA/RS','PETERSON DONIZETE GOMES DA SILVA',NULL,15,'RUA/AVENIDA: TIRADENTES, 527 - CENTRO','Casca','RS','99260-000',false),
  ('REGIONAL 010','CERRO LARGO / RS','PETERSON DONIZETE GOMES DA SILVA',NULL,0,'AVENIDA CEL. JORGE FRANTZ, 71 - CENTRO','Cerro Largo','RS','97900-000',false),
  ('REGIONAL 010','CHAPADA/RS','PETERSON DONIZETE GOMES DA SILVA',NULL,63,'Rua Padre Tiago Kliger, 271 - Progresso','Chapada','RS','99530-000',false),
  ('REGIONAL 010','FLORESTA/RS','PETERSON DONIZETE GOMES DA SILVA',NULL,2,'TRAVESSA CAÇAPAVA, 70 - Floresta','Carazinho','RS','99500-000',false),
  ('REGIONAL 010','GIRUÁ/RS','PETERSON DONIZETE GOMES DA SILVA',NULL,0,'RUA JULIO DE CASTILHO, 125 - SEGUER','Giruá','RS','98870-000',false),
  ('REGIONAL 010','HIPICA/RS','PETERSON DONIZETE GOMES DA SILVA',NULL,0,'Av. Castelo Branco, 691, 691 - HIPICA','Carazinho','RS','99500-000',false),
  ('REGIONAL 010','MARAU/RS','PETERSON DONIZETE GOMES DA SILVA',NULL,76,'AVENIDA JOÃO POSSER, 1166 MARAU-RS, - CENTRO','Maraú','BA','99150-000',false),
  ('REGIONAL 010','NOVO BARREIRO/RS','PETERSON DONIZETE GOMES DA SILVA',NULL,0,'RUA PALMITAL, 167 - CENTRO','Novo Barreiro','RS','99505-000',false),
  ('REGIONAL 010','ORIENTAL','PETERSON DONIZETE GOMES DA SILVA',NULL,0,'RUA PERNAMBUCO, 456 - ORIENTAL','Carazinho','RS','99500-000',false),
  ('REGIONAL 010','PASSO FUNDO/RS','PETERSON DONIZETE GOMES DA SILVA',NULL,38,'RUA MANAUS, 8 - PQ RECREIO','Passo Fundo','RS','99010-050',false),
  ('REGIONAL 010','PINHEIRO MARCADO','PETERSON DONIZETE GOMES DA SILVA',NULL,0,'ARTHUR BERNARDES, 203 - Sassi','Carazinho','RS','99500-000',false),
  ('REGIONAL 010','ROGOSWSKI / RS','PETERSON DONIZETE GOMES DA SILVA',NULL,1,'TRAVESSA SERANDI, 75 - ROGOSWSKI','Santo Ângelo','RS','98802-100',false),
  ('REGIONAL 010','SÃO LUIZ GONZAGA','PETERSON DONIZETE GOMES DA SILVA',NULL,0,'DEZESSEIS DE NOVEMBRO, - DISTRITO LARANJAL','Santo Ângelo','RS','98801-850',false),
  ('REGIONAL 010','SÃO LUIZ GONZAGA / RS','PETERSON DONIZETE GOMES DA SILVA',NULL,26,'RUA JOÃO GOULART, 1240 - DA GRUTA','São Luiz','RR','97800-970',false),
  ('REGIONAL 010','SUB - NAO ME TOQUE/RS','PETERSON DONIZETE GOMES DA SILVA',NULL,1,'RUA ALTO JAQUI, 31 - CENTRO','Não-Me-Toque','RS','99470-000',false),
  ('REGIONAL 010','TAPEJARA/RS','PETERSON DONIZETE GOMES DA SILVA',NULL,44,'Rua Assis Brasil, 171 - CENTRO','Tapejara','RS','99950-000',false),
  ('REGIONAL 010','VILA MARIA / RS','PETERSON DONIZETE GOMES DA SILVA',NULL,11,'RUA BENJAMIN CONSTANT, 644 - CENTRO','Vila Maria','RS',NULL,false),
  ('REGIONAL 012','CURITIBA/PR','MARCONES ALMEIDA DOS SANTOS','(41) 8850-9122',66,'Rua Arlindo Araújo Sobrinho, 541 - Guabirotuba','Curitiba','PR','81510-210',true),
  ('REGIONAL 012','SITIO CERCADO - NOVO HORIZONTE','MARCONES ALMEIDA DOS SANTOS',NULL,0,'Rua José Irineu Budant, 36 - SITIO CERCADO','Curitiba','PR','81935-308',false),
  ('REGIONAL 012','SITIO CERCADO OSTERNACK','MARCONES ALMEIDA DOS SANTOS',NULL,14,'Rua Lúcio de Oliveira Lara, 1107 - SITIO CERCADO','Curitiba','PR','81935-158',false),
  ('REGIONAL 013','CARUARU/PE','EDSON JOSE DA SILVA','(81) 99267-8579',143,'RUA PROSPERIDADE, 52 - Salgado','Caruaru','PE','55020-370',true),
  ('REGIONAL 013','CACHOEIRINHA / PE CENTRO','EDSON JOSE DA SILVA',NULL,70,'Rua Siqueira Campos, 42 - CENTRO','Cachoeirinha','PE','55380-000',false),
  ('REGIONAL 013','CACHOEIRINHA / PE NOÉMIA','EDSON JOSE DA SILVA',NULL,15,'RUA ALICE RODRIGUES DA SILVA, 45 - TÉRRIO','Cachoeirinha','PE','55380-000',false),
  ('REGIONAL 013','JOSE CARLOS DE OLIVEIRA/PE','EDSON JOSE DA SILVA',NULL,16,'RUA JOSE AUGUSTO, 545 - JOSE CARLOS DE OLIVEIRA','Caruaru','PE','55000-000',false),
  ('REGIONAL 013','JOSÉ LIBERATO/PE','EDSON JOSE DA SILVA',NULL,43,'RUA INDIO GUARANI, 48, 48 - JOSÉ LIBERATO','Caruaru','PE','55000-000',false),
  ('REGIONAL 013','PESQUEIRA CENTENARIO/PE','EDSON JOSE DA SILVA',NULL,19,'RUA VISTA ALEGRE, 79 - CENTENARIO','Pesqueira','PE','55200-000',false),
  ('REGIONAL 013','SANHARÓ/PE','EDSON JOSE DA SILVA',NULL,38,'RUA ONIAS LEITE, 21 - CAJAZEIRA','Sanharó','PE','55200-005',false),
  ('REGIONAL 013','SÃO FRANCISCO - CARUARU','EDSON JOSE DA SILVA',NULL,41,'AVENIDA RIO DE JANEIRO, 80 - São Francisco','Caruaru','PE','55006-240',false),
  ('REGIONAL 013','SÃO JOÃO DA ESCÓCIA/PE','EDSON JOSE DA SILVA',NULL,36,'RUA DEPUTADO ULISSES GUIMARÃES, 134 - SÃO J. ESCOCIA','Caruaru','PE','55200-000',false),
  ('REGIONAL 013','SUB - PETROPOLIS','EDSON JOSE DA SILVA',NULL,37,'Rua Martins Afonso, 142 - São Francisco','Caruaru','PE','55006-280',false),
  ('REGIONAL 013','SUB - VILA DO AEROPORTO/PE','EDSON JOSE DA SILVA',NULL,0,'Avenida Leão Dourado, 3232 - Kennedy','Caruaru','PE','55036-000',false),
  ('REGIONAL 013','SUB - VILA IGREJINHA','EDSON JOSE DA SILVA',NULL,0,'Rua José Vicente Ferreira, S/N - Tacaimbó','Tacaimbó','PE','55140-000',false),
  ('REGIONAL 013','SUB - VILA PELADAS','EDSON JOSE DA SILVA',NULL,13,'VILA PELADAS, - VILA PELADAS','Caruaru','PE','55000-000',false),
  ('REGIONAL 013','SUB- RIACHO DOCE','EDSON JOSE DA SILVA',NULL,15,'POVOADO RIACHO DOCE, 82 - Riacho Doce','Caruaru','PE','55000-000',false)
) AS c(grupo, nome, dirigente, celular, membros, endereco, cidade, uf, cep, lider);
