-- Import de igrejas — REGIONAL 019 (66 igrejas, líder VANDERLEI
-- RODRIGUES VIEIRA). Conteúdo gerado a partir dos dados já aplicados
-- em produção (conferido via SELECT direto no banco), mesmo padrão
-- units→churches das migrations 079-083.

INSERT INTO public.units (type, name, parent_id, is_headquarters, is_sector_mother, status)
SELECT 'IGREJA', v.nome, (SELECT id FROM public.units WHERE type='SETOR' AND name='REGIONAL 019'), false, v.lider, 'ACTIVE'
FROM (VALUES
  ('MACEIÓ/AL', true),('ASSENTAMENTO CATUCÁ/AL', false),('ATALAIA/AL', false),
  ('BARRA DE CAMARAGIBE/AL', false),('BARRA DE SANTO ANTONIO/AL', false),
  ('BEIRA RIO - MACEIÓ/AL', false),('BENEDITO BENTES I - MACEIÓ/AL', false),
  ('BENEDITO BENTES II - ALVES CORREIA', false),('BENEDITO BENTES II - BELA VISTA', false),
  ('BOM DESPACHO/AL', false),('CAJUEIRO / AL', false),('CAMPESTRE/AL', false),
  ('CAMPOS FRIOS/PE', false),('CAPELA/AL', false),('CLETO MARQUES LUZ - MACEIÓ/AL', false),
  ('CLIMA BOM - MACEIÓ/AL', false),('COLINA', false),('COLONIA LEOPOLDINA/AL', false),
  ('COM. PAU D''ARCO - MACEIÓ/AL', false),('COMUNIDADE SÃO RAFAEL I - MACEIÓ/AL', false),
  ('COMUNIDADE SÃO RAFAEL II - MACEIÓ/AL', false),('COMUNIDADE SÃO RAFAEL III - MACEIÓ/AL', false),
  ('DENISSON MENESES - GAMA LINS', false),('FEITOSA - MACEIÓ/AL', false),
  ('FINAL DO JACINTINHO - MACEIÓ/AL', false),('GUAXUMA - MACEIÓ/AL', false),
  ('JUNDIÁ/AL', false),('MARECHAL DEODORO/AL', false),('MARIBONDO/AL', false),
  ('MOACIR ANDRADE - MACEIÓ/AL', false),('NAÇÕES UNIDAS - MACEIÓ/AL', false),
  ('NOVO HORIZONTE - MACEIÓ/AL', false),('NOVO LINO/AL', false),
  ('PALMEIRA DOS ÍNDIOS/AL', false),('PARIPUEIRA/AL', false),('PEDRA GRANDE/AL', false),
  ('PIABAS - MACEIÓ/AL', false),('PORTO DE PEDRAS/AL', false),('PRADO - MACEIÓ/AL', false),
  ('RIO LARGO/AL', false),('RUA BELÉM - MACEIÓ/AL', false),
  ('RUA SANTO ANTÔNIO - MACEIÓ/AL', false),('SÃO LUIZ DO QUITUNDE/AL', false),
  ('SERTÃOZINHO/AL', false),('SUB - BAIRRO NOSSO - RIO LARGO/AL', false),
  ('SUB - BELO JARDIM - COLONIA LEOPOLDINA/AL', false),
  ('SUB - CLOVIS ANDRADE - CAMPESTRE/AL', false),
  ('SUB - CONJ. FREI DAMIÃO - B. BENTES BELA VISTA/AL', false),
  ('SUB - CONJ. JOSEFA ANDRADE - ATALAIA/AL', false),
  ('SUB - ENGENHO TEREZINHA - CAMPESTRE/AL', false),('SUB - FLEXEIRAS/AL', false),
  ('SUB - JOSÉ DIAS - MARECHAL DEODORO/AL', false),
  ('SUB - MARIA QUIRINO - COLONIA LEOPOLDINA/AL', false),('SUB - MESSIAS/AL', false),
  ('SUB - PARARIS DE BAIXO - SÃO LUIZ DO QUITUNDE/AL', false),
  ('SUB - PARARIS DE CIMA - SÃO LUIZ DO QUITUNDE/AL', false),
  ('SUB - PIAU - PIRANHAS/AL', false),('SUB - POV. TAQUARANA - MARIBONDO/AL', false),
  ('SUB - SANTA RITA - COLONIA LEOPOLDINA/AL', false),
  ('SUB - SANTA TEREZA - CAMPESTRE/AL', false),
  ('SUB - TEOTONIO VILELA - RIO LARGO/AL', false),
  ('SUB - VILA NOVA - COLONIA LEOPOLDINA/AL', false),
  ('SUB-OLHO D''ÁGUA - ATALAIA /AL', false),
  ('TRAVESSA DA JARDINEIRA - MACEIÓ/AL', false),('VIÇOSA/AL', false),
  ('VILLAGE CAMPESTRE II - MACEIÓ/AL', false)
) AS v(nome, lider);

INSERT INTO public.churches (name, pastor_name, pastor_phone, member_count, address, city, state, zip_code, unit_id, is_sector_head, status)
SELECT c.nome, c.dirigente, c.celular, c.membros, c.endereco, c.cidade, c.uf, c.cep,
  (SELECT id FROM public.units WHERE type='IGREJA' AND name=c.nome AND parent_id=(SELECT id FROM public.units WHERE type='SETOR' AND name='REGIONAL 019')),
  c.lider, 'ACTIVE'
FROM (VALUES
  ('MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA','(19) 99930-7486',107,'Rua Maria Pinheiro dos Santos, 216 - Jacintinho','Maceió','AL','57041-170',true),
  ('ASSENTAMENTO CATUCÁ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,13,'Assentamento Catucá, - ZONA RURAL','Catu','BA','57920-000',false),
  ('ATALAIA/AL','VANDERLEI RODRIGUES VIEIRA',NULL,37,'CONJUNTO SÃO SEBASTIÃO, S/Nº, - JOSÉ PAULINO','Atalaia','AL','57690-000',false),
  ('BARRA DE CAMARAGIBE/AL','VANDERLEI RODRIGUES VIEIRA',NULL,17,'Rua N. B.de Camaragibe, - Lt S.José','Passo de Camaragibe','AL','57930-000',false),
  ('BARRA DE SANTO ANTONIO/AL','VANDERLEI RODRIGUES VIEIRA',NULL,22,'Rua Amaro Soares dos Santos, 45 - CENTRO','Santo Antônio','RN','57925-000',false),
  ('BEIRA RIO - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,11,'Rua Beira Rio, 9 - CRUZ DAS ALMAS','Maceió','AL','57038-186',false),
  ('BENEDITO BENTES I - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,13,'Avenida Garça Torta, 512 - QD A39','Maceió','AL','57084-040',false),
  ('BENEDITO BENTES II - ALVES CORREIA','VANDERLEI RODRIGUES VIEIRA',NULL,14,'Rua Radialista Alves Correia, s/nº, 0 - Benedito Bentes','Maceió','AL','57084-648',false),
  ('BENEDITO BENTES II - BELA VISTA','VANDERLEI RODRIGUES VIEIRA',NULL,20,'Rua Benedito Bentes II, 18 - QD 04','Maceió','AL','57061-110',false),
  ('BOM DESPACHO/AL','VANDERLEI RODRIGUES VIEIRA',NULL,9,'Rua da Casa de Farinha, - CENTRO','Passo de Camaragibe','AL','57930-000',false),
  ('CAJUEIRO / AL','VANDERLEI RODRIGUES VIEIRA',NULL,6,'Rua Nova, s/nº, - CENTRO','Cajueiro','AL','57770-000',false),
  ('CAMPESTRE/AL','VANDERLEI RODRIGUES VIEIRA',NULL,95,'Travessa Rui Palmeira, s/nº, - CENTRO','Campestre','AL','57968-000',false),
  ('CAMPOS FRIOS/PE','VANDERLEI RODRIGUES VIEIRA',NULL,57,'Rua Peciliano Barbosa, s/nº, - CENTRO','Xexéu','PE','55555-000',false),
  ('CAPELA/AL','VANDERLEI RODRIGUES VIEIRA',NULL,36,'X, - CENTRO','Capela','AL','57780-000',false),
  ('CLETO MARQUES LUZ - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,29,'Travessa Getsemani, 12 - TABULEIRO DOS MARTINS','Maceió','AL','57061-110',false),
  ('CLIMA BOM - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,14,'Rua Santa Rita, 22 - CLIMA BOM','Maceió','AL','57061-110',false),
  ('COLINA','VANDERLEI RODRIGUES VIEIRA',NULL,14,'AV. GENERAL WALFRIDO JERÔNIMO DA ROCHA, 24 - CLIMA BOM','Maceió','AL','57690-000',false),
  ('COLONIA LEOPOLDINA/AL','VANDERLEI RODRIGUES VIEIRA',NULL,50,'Jardim, s/nº, 0 - CENTRO','Colônia Leopoldina','AL','57975-000',false),
  ('COM. PAU D''ARCO - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,41,'Rua Divaldo Franco S/Nº, 0 - Jacintinho','Maceió','AL','57040-360',false),
  ('COMUNIDADE SÃO RAFAEL I - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,27,'Rua Grota do Rafael, 20 - Jacintinho','Maceió','AL','57040-676',false),
  ('COMUNIDADE SÃO RAFAEL II - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,16,'Rua Bela Vista, s/nº, 0 - Jacintinho','Maceió','AL','57041-050',false),
  ('COMUNIDADE SÃO RAFAEL III - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,7,'1ª Travessa Bela Vista, 13 - Jacintinho','Maceió','AL','57040-045',false),
  ('DENISSON MENESES - GAMA LINS','VANDERLEI RODRIGUES VIEIRA',NULL,4,'Conj Hab., 16 - QD 03','Maceió','AL','57061-110',false),
  ('FEITOSA - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,22,'Avenida Governador Lamenha Filho, 864 - Feitosa','Maceió','AL','57043-000',false),
  ('FINAL DO JACINTINHO - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,4,'Rua Durval Guimarães, s/nº, - CONJ. MUTIRÃO II','Maceió','AL','57040-844',false),
  ('GUAXUMA - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,8,'Rua Alto Boa Vista, s/nº, 0 - Guaxuma','Maceió','AL','57038-760',false),
  ('JUNDIÁ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,36,'Conjunto João Rufino, s/nº, - CENTRO','Jundiá','AL','57965-000',false),
  ('MARECHAL DEODORO/AL','VANDERLEI RODRIGUES VIEIRA',NULL,39,'Rua João de Faria Lobo, s/nº, 0 - TAPERAGUA','Marechal Deodoro','AL','57160-000',false),
  ('MARIBONDO/AL','VANDERLEI RODRIGUES VIEIRA',NULL,15,'Rua do Comercio, 3 - CENTRO','Maribondo','AL','57670-000',false),
  ('MOACIR ANDRADE - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,6,'Quadra 15 (Cj Moacir Andrade), 5 - QD 04','Maceió','AL','57086-198',false),
  ('NAÇÕES UNIDAS - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,38,'Avenida Nações Unidas, 108 - Santa Lucia','Maceió','AL','57082-105',false),
  ('NOVO HORIZONTE - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,9,'RUA NOVO HORIZONTE, 0 - CRUZ DAS ALMAS','Maceió','AL','57040-575',false),
  ('NOVO LINO/AL','VANDERLEI RODRIGUES VIEIRA',NULL,41,'Rua Bom Destino II, s/nº, - CENTRO','Atalaia','AL','57690-000',false),
  ('PALMEIRA DOS ÍNDIOS/AL','VANDERLEI RODRIGUES VIEIRA',NULL,13,'Rua Dondon Tobias, S/Nº, - PARAISO','Palmeira dos Índios','AL','57602-160',false),
  ('PARIPUEIRA/AL','VANDERLEI RODRIGUES VIEIRA',NULL,5,'CEP Município, - AO LADO DA CAMARA DOS VEREADORES','Paripueira','AL','57935-000',false),
  ('PEDRA GRANDE/AL','VANDERLEI RODRIGUES VIEIRA',NULL,9,'CENTRO, 0 - JARAGUA,123','Pedra Grande','RN','57160-000',false),
  ('PIABAS - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,28,'Rua São Luiz, 22 - Jacintinho','Maceió','AL','57042-140',false),
  ('PORTO DE PEDRAS/AL','VANDERLEI RODRIGUES VIEIRA',NULL,18,'Conjunto Agenor F. de Ataide, s/nº, - CENTRO','Porto de Pedras','AL','57945-000',false),
  ('PRADO - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,9,'Rua Miramar, 102 - PRADO','Maceió','AL','57010-180',false),
  ('RIO LARGO/AL','VANDERLEI RODRIGUES VIEIRA',NULL,36,'Rua do Matadouro, - MULTIRAO','Rio Largo','AL','57100-000',false),
  ('RUA BELÉM - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,18,'Rua Belém, 277 - Jacintinho','Maceió','AL','57040-020',false),
  ('RUA SANTO ANTÔNIO - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,22,'Rua Santo Antônio, 312 - Jacintinho','Maceió','AL','57040-000',false),
  ('SÃO LUIZ DO QUITUNDE/AL','VANDERLEI RODRIGUES VIEIRA',NULL,13,'Rua Santa Juliana, s/ nº, - CENTRO','São Luiz','RR','57920-000',false),
  ('SERTÃOZINHO/AL','VANDERLEI RODRIGUES VIEIRA',NULL,14,'Rua Posto de Mota, s/nº, - CENTRO','Maraial','PE','55405-000',false),
  ('SUB - BAIRRO NOSSO - RIO LARGO/AL','VANDERLEI RODRIGUES VIEIRA',NULL,11,'Rua Bar Nosso, 2000 - A','Rio Largo','AL','57061-110',false),
  ('SUB - BELO JARDIM - COLONIA LEOPOLDINA/AL','VANDERLEI RODRIGUES VIEIRA',NULL,12,'Zona Rural, - ZONA RURAL','Jardim','CE','57061-110',false),
  ('SUB - CLOVIS ANDRADE - CAMPESTRE/AL','VANDERLEI RODRIGUES VIEIRA',NULL,14,'CEP Município, - ZONA RURAL','Campestre','AL','57968-000',false),
  ('SUB - CONJ. FREI DAMIÃO - B. BENTES BELA VISTA/AL','VANDERLEI RODRIGUES VIEIRA',NULL,6,'Rua C 83, 45 - LADEIRA DA PAZ','Maceió','AL','57085-033',false),
  ('SUB - CONJ. JOSEFA ANDRADE - ATALAIA/AL','VANDERLEI RODRIGUES VIEIRA',NULL,9,'CONJ. JOSEFA ANDRADE DE SOUZA, - URBANO','Atalaia','AL','57690-991',false),
  ('SUB - ENGENHO TEREZINHA - CAMPESTRE/AL','VANDERLEI RODRIGUES VIEIRA',NULL,18,'CEP Município, - ZONA RURAL','Campestre','AL','57968-000',false),
  ('SUB - FLEXEIRAS/AL','VANDERLEI RODRIGUES VIEIRA',NULL,0,'RUA PAULO CAVALCANTE LINS, - CENTRO','Flexeiras','AL','57995-000',false),
  ('SUB - JOSÉ DIAS - MARECHAL DEODORO/AL','VANDERLEI RODRIGUES VIEIRA',NULL,4,'Lot Terra da Esperança, 15 - QD F','Marechal Deodoro','AL','57061-110',false),
  ('SUB - MARIA QUIRINO - COLONIA LEOPOLDINA/AL','VANDERLEI RODRIGUES VIEIRA',NULL,6,'CEP Município, - ZONA RURAL','Mari','PB','57975-000',false),
  ('SUB - MESSIAS/AL','VANDERLEI RODRIGUES VIEIRA',NULL,1,'RUA MANOEL DUBEAUX LEÃO, 38 - CENTRO','Messias','AL','57990-000',false),
  ('SUB - PARARIS DE BAIXO - SÃO LUIZ DO QUITUNDE/AL','VANDERLEI RODRIGUES VIEIRA',NULL,12,'Zona Rural, - ZONA RURAL','São Luiz','RR','57061-110',false),
  ('SUB - PARARIS DE CIMA - SÃO LUIZ DO QUITUNDE/AL','VANDERLEI RODRIGUES VIEIRA',NULL,7,'Zona Rural, - ZONA RURAL','São Luiz','RR','57061-110',false),
  ('SUB - PIAU - PIRANHAS/AL','VANDERLEI RODRIGUES VIEIRA',NULL,17,'Rua da Palma, - CAPIÁ','Piranhas','AL','57460-000',false),
  ('SUB - POV. TAQUARANA - MARIBONDO/AL','VANDERLEI RODRIGUES VIEIRA',NULL,14,'Zona Rural, - ZONA RURAL','Maribondo','AL','57061-110',false),
  ('SUB - SANTA RITA - COLONIA LEOPOLDINA/AL','VANDERLEI RODRIGUES VIEIRA',NULL,19,'Zona Rural, - ZONA RURAL','Santa Rita','MA','57061-110',false),
  ('SUB - SANTA TEREZA - CAMPESTRE/AL','VANDERLEI RODRIGUES VIEIRA',NULL,17,'CEP Município, - ZONA RURAL','Campestre','AL','57968-000',false),
  ('SUB - TEOTONIO VILELA - RIO LARGO/AL','VANDERLEI RODRIGUES VIEIRA',NULL,10,'Conj. Habitacional, 1 - QD 1','Rio Largo','AL','57061-110',false),
  ('SUB - VILA NOVA - COLONIA LEOPOLDINA/AL','VANDERLEI RODRIGUES VIEIRA',NULL,3,'POVOADO VILA NOVA, - Vila Nova','Colônia Leopoldina','AL','57975-000',false),
  ('SUB-OLHO D''ÁGUA - ATALAIA /AL','VANDERLEI RODRIGUES VIEIRA',NULL,10,'Povoado Olhos d''Água, s/ nº, - SAPÉ','Atalaia','AL','57690-000',false),
  ('TRAVESSA DA JARDINEIRA - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,11,'Travessa da Jardineira (Armando Wucherer), 39 - Jacintinho','Maceió','AL','57040-125',false),
  ('VIÇOSA/AL','VANDERLEI RODRIGUES VIEIRA',NULL,15,'Rua Dr. Jaime Carneiro, 138 - CENTRO','Viçosa','AL','57700-000',false),
  ('VILLAGE CAMPESTRE II - MACEIÓ/AL','VANDERLEI RODRIGUES VIEIRA',NULL,14,'Rua São Pedro, 46 - Cidade Universitária','Maceió','AL','57073-550',false)
) AS c(nome, dirigente, celular, membros, endereco, cidade, uf, cep, lider);
