-- Import de igrejas — REGIONAL 020, 021, 022, 023, 025, 026.
-- Conteúdo gerado a partir dos dados já aplicados em produção
-- (conferido via SELECT direto no banco), mesmo padrão units→churches.

INSERT INTO public.units (type, name, parent_id, is_headquarters, is_sector_mother, status)
SELECT 'IGREJA', v.nome, (SELECT id FROM public.units WHERE type='SETOR' AND name=v.grupo), false, v.lider, 'ACTIVE'
FROM (VALUES
  ('REGIONAL 020','JOÃO PESSOA/PB',true),
  ('REGIONAL 021','PUXINANÃ/PB',true),('REGIONAL 021','CAXANGÁ/PB',false),
  ('REGIONAL 021','DEUS PROVERÁ/PB',false),('REGIONAL 021','JARDIM QUARENTA/PB',false),
  ('REGIONAL 021','LAGOA DE JOÃO GOMES/PB',false),('REGIONAL 021','LAGOA SECA/PB',false),
  ('REGIONAL 021','MARACAJÁ/PB',false),('REGIONAL 021','MONTADAS/PB',false),
  ('REGIONAL 021','SITIO CAXANGÁ/PB',false),('REGIONAL 021','VAL DE JABOQUE/PB',false),
  ('REGIONAL 022','VERGEL - MACEIÓ/AL',true),('REGIONAL 022','AREIAS I - RECIFE/PE',false),
  ('REGIONAL 022','COLONIA DE PIUM - RN',false),('REGIONAL 022','CONJ. CIDADE SORRISO I - MACEIÓ/AL',false),
  ('REGIONAL 022','CONJ. MUTIRÃO I - MACEIÓ/AL',false),('REGIONAL 022','IPIOCA - MACEIÓ/AL',false),
  ('REGIONAL 022','SUB - AREIAS II - RECIFE/PE',false),('REGIONAL 022','SUB - MACEIÓ I - MACEIÓ/AL',false),
  ('REGIONAL 022','SUB - SELMA BANDEIRA MACEIO/AL',false),('REGIONAL 022','SUB- ROTEIRO/AL',false),
  ('REGIONAL 023','CATEDRAL - SALVADOR/BA',true),('REGIONAL 023','LAGOINHA/BA',false),
  ('REGIONAL 023','NOVA BRASILIA/BA',false),('REGIONAL 023','SUB - VILA VALERIA/BA',false),
  ('REGIONAL 023','SUB-AGUAS CLARAS',false),('REGIONAL 023','SUB-CALDEIRÃO DE SÃO GABRIEL/BA',false),
  ('REGIONAL 023','SUB-IRECE/BA',false),('REGIONAL 023','SUB-MUSSURUNGA I',false),
  ('REGIONAL 023','SUB-SÃO DOMINGOS /BA',false),('REGIONAL 023','SUB-VALERIA I',false),
  ('REGIONAL 025','SIMÕES FILHO/BA',true),
  ('REGIONAL 026','GRAVATÁ/PE',true),('REGIONAL 026','BEZERROS/PE',false),
  ('REGIONAL 026','SUB - CARICÉ',false),('REGIONAL 026','SUB- CONGREGAÇÃO LIDIA QUEIROZ',false),
  ('REGIONAL 026','SUB-CAIQUE',false),('REGIONAL 026','SUB-VITÓRIA DE SANTO ANTÃO / PE LEAL',false)
) AS v(grupo, nome, lider);

INSERT INTO public.churches (name, pastor_name, pastor_phone, member_count, address, city, state, zip_code, unit_id, is_sector_head, status)
SELECT c.nome, c.dirigente, c.celular, c.membros, c.endereco, c.cidade, c.uf, c.cep,
  (SELECT id FROM public.units WHERE type='IGREJA' AND name=c.nome AND parent_id=(SELECT id FROM public.units WHERE type='SETOR' AND name=c.grupo)),
  c.lider, 'ACTIVE'
FROM (VALUES
  ('REGIONAL 020','JOÃO PESSOA/PB','ALEXANDRO FRUTUOSO DA COSTA','(83) 99920-9334',100,'Rua Raul Cordula, 199 - ALTO','João Pessoa','PB','58090-500',true),
  ('REGIONAL 021','PUXINANÃ/PB','JOSE RAMALHO DE SANTANA',NULL,1,'Rua do Angrão, 1283 - SITIO ANTAS','Puxinanã','PB','13400-000',true),
  ('REGIONAL 021','CAXANGÁ/PB','JOSE RAMALHO DE SANTANA',NULL,0,'RUA SITIO CAXANGÁ, - ZONA RURAL','Lagoa Seca','PB','58117-000',false),
  ('REGIONAL 021','DEUS PROVERÁ/PB','JOSE RAMALHO DE SANTANA',NULL,0,'SITIO ANTAS II, - SITIO ANTAS','Vera','MT','13400-000',false),
  ('REGIONAL 021','JARDIM QUARENTA/PB','JOSE RAMALHO DE SANTANA',NULL,0,'Rua Santa Rita, - Quarenta','Campina Grande','PB','58416-240',false),
  ('REGIONAL 021','LAGOA DE JOÃO GOMES/PB','JOSE RAMALHO DE SANTANA',NULL,0,'Avenida Marechal Floriano Peixoto, - CENTRO','Campina Grande','PB','58100-000',false),
  ('REGIONAL 021','LAGOA SECA/PB','JOSE RAMALHO DE SANTANA',NULL,0,'Rua Sérgio Augustinho Souza, 216 - CENTRO','Lagoa Seca','PB','13400-000',false),
  ('REGIONAL 021','MARACAJÁ/PB','JOSE RAMALHO DE SANTANA',NULL,0,'SITIO MARACAJÁ, - ZONA RURAL','Maracajá','SC','58115-000',false),
  ('REGIONAL 021','MONTADAS/PB','JOSE RAMALHO DE SANTANA',NULL,0,'Rua São José, 209 - CENTRO','Montadas','PB','13400-000',false),
  ('REGIONAL 021','SITIO CAXANGÁ/PB','JOSE RAMALHO DE SANTANA',NULL,0,'SITIO CAXANGÁ, - LAGOA SECA','Lagoa Seca','PB','13400-000',false),
  ('REGIONAL 021','VAL DE JABOQUE/PB','JOSE RAMALHO DE SANTANA',NULL,0,'Rua Maria José, 209 - CENTRO','Montadas','PB','13400-000',false),
  ('REGIONAL 022','VERGEL - MACEIÓ/AL','EZEQUIEL FRANCISCO DE LIMA','(82) 98838-1595',59,'Rua São Félix, 132 - Vergel do Lago','Maceió','AL','57015-200',true),
  ('REGIONAL 022','AREIAS I - RECIFE/PE','EZEQUIEL FRANCISCO DE LIMA',NULL,20,'RUA DOS PRAZERES, 890 - AREIAS','Recife','PE','50860-390',false),
  ('REGIONAL 022','COLONIA DE PIUM - RN','EZEQUIEL FRANCISCO DE LIMA',NULL,30,'RUA FRANCISCO REGINALDO CHAVIER DE SOUZA, QUADRA 01, 5 - ZONA RURAL','Pium','TO','59164-000',false),
  ('REGIONAL 022','CONJ. CIDADE SORRISO I - MACEIÓ/AL','EZEQUIEL FRANCISCO DE LIMA',NULL,76,'Avenida Principal B, - Benedito Bentes','Maceió','AL','57086-080',false),
  ('REGIONAL 022','CONJ. MUTIRÃO I - MACEIÓ/AL','EZEQUIEL FRANCISCO DE LIMA',NULL,8,'Quadra 3, 49 - Vergel do Lago','Maceió','AL','57015-200',false),
  ('REGIONAL 022','IPIOCA - MACEIÓ/AL','EZEQUIEL FRANCISCO DE LIMA',NULL,46,'Rua São Miguel, 227 - Ipioca','Maceió','AL','57039-880',false),
  ('REGIONAL 022','SUB - AREIAS II - RECIFE/PE','EZEQUIEL FRANCISCO DE LIMA',NULL,4,'RUA SENADOR THOMAZ LOBO, 55 - AREIAS','Recife','PE','50860-240',false),
  ('REGIONAL 022','SUB - MACEIÓ I - MACEIÓ/AL','EZEQUIEL FRANCISCO DE LIMA',NULL,3,'Quadra G, 15 - 15 A','Maceió','AL','57072-278',false),
  ('REGIONAL 022','SUB - SELMA BANDEIRA MACEIO/AL','EZEQUIEL FRANCISCO DE LIMA',NULL,8,'Rua O-1 CONJUNTO SELMA BANDEIRA.QD.B, 38 - Benedito Bentes','Maceió','AL','57086-268',false),
  ('REGIONAL 022','SUB- ROTEIRO/AL','EZEQUIEL FRANCISCO DE LIMA',NULL,4,'RUA PEDRO BALBINO, 302 - CENTRO','Roteiro','AL','57257-000',false),
  ('REGIONAL 023','CATEDRAL - SALVADOR/BA','ADENILSON EVANGELISTA DE ARAÚJO','(81) 99595-3795',174,'Rua Direita de Valéria - Valéria','Salvador','BA','41305-340',true),
  ('REGIONAL 023','LAGOINHA/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,9,'RUA DO CHAFARIZ, - POVOADO DE LAGOINHA','São Gabriel','BA','44915-000',false),
  ('REGIONAL 023','NOVA BRASILIA/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,44,'Rua Boca da Mata, 159 - Valéria','Salvador','BA','41300-460',false),
  ('REGIONAL 023','SUB - VILA VALERIA/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,1,'RUA E, 9ª TRAVESSA, 30 - Valéria','Salvador','BA','41307-322',false),
  ('REGIONAL 023','SUB-AGUAS CLARAS','ADENILSON EVANGELISTA DE ARAÚJO',NULL,0,'Rua Frank Nalva, 44 - AGUAS CLARAS','Salvador','BA','41310-340',false),
  ('REGIONAL 023','SUB-CALDEIRÃO DE SÃO GABRIEL/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,1,'RUA TAIZ MELO ,POVOADO DE CALDEIRÃO DE FLORINDO, 21 - CENTRO','São Gabriel','BA',NULL,false),
  ('REGIONAL 023','SUB-IRECE/BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,19,'Rua Jacobina, 710 - São José','Irecê','BA','44867-100',false),
  ('REGIONAL 023','SUB-MUSSURUNGA I','ADENILSON EVANGELISTA DE ARAÚJO',NULL,0,'Rua Professor Plínio Garcez de Sena, 97 - Mussurunga II','Salvador','BA','41480-225',false),
  ('REGIONAL 023','SUB-SÃO DOMINGOS /BA','ADENILSON EVANGELISTA DE ARAÚJO',NULL,16,'POVOADO DE SÃO DOMINGOS, - SAO DOMINGOS','Souto Soares','BA','46990-000',false),
  ('REGIONAL 023','SUB-VALERIA I','ADENILSON EVANGELISTA DE ARAÚJO',NULL,13,'Rua Jardim Novo Horizonte, 52 - Valéria','Salvador','BA','41300-015',false),
  ('REGIONAL 025','SIMÕES FILHO/BA','ROBÉRIO FONSECA DA COSTA','(71) 98187-9090',13,'Rua do Condomínio João Filgueiras Simões Filho, 542 - Ponto de Parada','Simões Filho','BA','43713-345',true),
  ('REGIONAL 026','GRAVATÁ/PE','ANTONIO LAURINDO DA SILVA','(19) 98160-1563',80,'Rua Quinze de Novembro, 673 - NOSSA SENHORA DAS GRAÇAS','Gravatá','PE','55642-550',true),
  ('REGIONAL 026','BEZERROS/PE','ANTONIO LAURINDO DA SILVA',NULL,0,'RUA N. S. DE APARECIDA, 66 - STO AMARO','Bezerros','PE','55660-000',false),
  ('REGIONAL 026','SUB - CARICÉ','ANTONIO LAURINDO DA SILVA',NULL,15,'SITIO CARICÉ, - CARICÉ','Piracicaba','SP','55600-000',false),
  ('REGIONAL 026','SUB- CONGREGAÇÃO LIDIA QUEIROZ','ANTONIO LAURINDO DA SILVA',NULL,2,'RUA LIDIA QUEIROZ COSTA, 123 - Lídia Queiroz','Queiroz','SP','55614-000',false),
  ('REGIONAL 026','SUB-CAIQUE','ANTONIO LAURINDO DA SILVA',NULL,15,'RUA MAJOR EXPEDITO, 140 - A','Vitória de Santo Antão','PE','55600-000',false),
  ('REGIONAL 026','SUB-VITÓRIA DE SANTO ANTÃO / PE LEAL','ANTONIO LAURINDO DA SILVA',NULL,22,'RUA MARIA DE JESUS, 477 - ALTO JOSÉ LEAL','Vitória de Santo Antão','PE','55608-230',false)
) AS c(grupo, nome, dirigente, celular, membros, endereco, cidade, uf, cep, lider);
