-- 100_seed_banco_questoes_licao_bibliologia_homiletica.sql
-- (Renumerada de 096 para 100 em 12/09/2026 — ver nota no topo de
-- 099_banco_questoes_licao_pool_sorteio.sql sobre o motivo da renumeração.)
--
-- Popula avaliacoes_banco_questoes_licao (criada na migration 099) com
-- os 296 itens verificados item a item contra BIBLIOLOGIA.pdf/HOMILETICA.pdf
-- (Curso Médio) + GABARITO EXERCICIOS.pdf (Bibliologia e Homilética),
-- extraídos em docs/banco_questoes.csv. O item 7.10 de Homilética
-- (questão dissertativa, sem gabarito objetivo) foi excluído do banco
-- de sorteio por decisão do Joaquim em 12/09/2026.
--
-- Estratégia: carrega os dados brutos (mesmas colunas do CSV) numa
-- tabela auxiliar temporária, transforma formato/opções por tipo de
-- questão com SQL (evita erro de transcrição manual de JSON), e depois
-- remove a tabela auxiliar. Aplicada manualmente no staging em
-- 12/09/2026 (ver README de supabase/migrations).

CREATE TABLE public._staging_banco_questoes_raw (
  materia text NOT NULL,
  licao integer NOT NULL,
  item text NOT NULL,
  formato text NOT NULL,
  enunciado text NOT NULL,
  alternativas text,
  resposta_correta text NOT NULL,
  fonte text
);

INSERT INTO public._staging_banco_questoes_raw (materia, licao, item, formato, enunciado, alternativas, resposta_correta, fonte) VALUES
('Bibliologia',1,'1.1','Certo/Errado','Atribui-se a João Calvino a disseminação do uso do vocábulo "Bíblia" para se referir à Palavra de Deus.','C/E','E','BIBLIOLOGIA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',1,'1.2','Certo/Errado','Originário do grego, o termo bíblia significa "livros", ou "coleção de pequenos livros".','C/E','C','BIBLIOLOGIA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',1,'1.3','Certo/Errado','A palavra bíblia é o plural de biblos.','C/E','C','BIBLIOLOGIA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',1,'1.4','Certo/Errado','O Criador, também revela-se através das Escrituras.','C/E','C','BIBLIOLOGIA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',1,'1.5','Múltipla escolha','A Bíblia é absolutamente necessária para alcançarmos a','a. vitória | b. vida eterna | c. bênção | d. Nenhuma das alternativas é correta','b','BIBLIOLOGIA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',1,'1.6','Múltipla escolha','A Palavra de Deus é de suma importância para o nosso crescimento','a. moral e espiritual | b. moral e físico | c. físico e espiritual | d. Todas as alternativas estão corretas','a','BIBLIOLOGIA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',1,'1.7','Múltipla escolha','As Escrituras são aptas para o aperfeiçoamento do salvo diante','a. da igreja | b. dos anjos | c. de Deus | d. Todas as alternativas estão corretas','c','BIBLIOLOGIA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',1,'1.8','Preencher lacuna','Vários ______ já foram escritos pelos homens ao longo de sua história.','(lacuna)','códigos','BIBLIOLOGIA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',1,'1.9','Preencher lacuna','O gênero humano não pode ser ______ à partir de preceitos humanos.','(lacuna)','regenerado','BIBLIOLOGIA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',1,'1.10','Preencher lacuna','A Palavra de Deus procede de Deus e são ______ ao coração do homem pelo Espírito Santo.','(lacuna)','aplicadas','BIBLIOLOGIA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',1,'1.11','Preencher lacuna','A Palavra de Deus se faz necessária à ______, pois sua lei moral é absoluta e imutável.','(lacuna)','humanidade','BIBLIOLOGIA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',1,'1.12','Certo/Errado','A história não é cíclica: é circular; não se repete.','C/E','C','BIBLIOLOGIA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',1,'1.13','Certo/Errado','Na Bíblia vemos que a história da humanidade e seus acontecimentos mais relevantes jamais foram obras do acaso.','C/E','C','BIBLIOLOGIA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',1,'1.14','Certo/Errado','O Senhor Jesus nos ensinou a rogarmos ao Pai para que venha o Apocalipse.','C/E','E','BIBLIOLOGIA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',1,'1.15','Certo/Errado','John Cromwell afirmou: "O que é a história, senão a manifestação de Deus?".','C/E','E','BIBLIOLOGIA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.1','Certo/Errado','A Palavra de Deus não trata sobre Deus e de sua relação com a humanidade.','C/E','E','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.2','Certo/Errado','O francês Chateaubriand diz ser a Bíblia insuperável em sua genialidade literária.','C/E','C','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.3','Certo/Errado','Sem a existência da Bíblia a literatura humana não seria tão rica e expressiva.','C/E','C','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.4','Certo/Errado','A Bíblia é, portanto, um dos livros contemporâneos de toda a humanidade, em todas as eras.','C/E','E','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.5','Múltipla escolha','O Liberalismo Teológico é uma corrente teológica que nasceu na','a. França | b. Inglaterra | c. Alemanha | d. Todas as alternativas estão corretas','c','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.6','Múltipla escolha','O Liberalismo tem como objetivo principal com relação as Escrituras','a. negar | b. validar | c. autorizar | d. Todas as alternativas estão corretas','a','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.7','Múltipla escolha','Muitos teólogos tem questionado com relação as Escrituras sua','a. eficácia | b. soberania | c. autoria | d. Todas as alternativas estão corretas','b','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.8','Múltipla escolha','Filosoficamente o Racionalismo dá prioridade','a. ao método | b. à doutrina | c. à razão | d. Todas as alternativas estão corretas','c','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.9','Certo/Errado','Os teólogos adeptos do racionalismo professavam sua fé na razão.','C/E','C','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.10','Certo/Errado','Emil Brunner, aliás, chegou a alcunhar a Palavra de Deus de "papa de papel".','C/E','C','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.11','Certo/Errado','Por trás de toda intensão liberal, está a certeza das consequências contidas na Palavra.','C/E','E','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.12','Certo/Errado','Diabo não tem conseguido infiltrar a teologia liberal em seminários teológicos conservadores.','C/E','E','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.13','Associação de colunas','A Bíblia é a Palavra de Deus','A - Neo-Ortodoxa | B - Conservadora','B','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.14','Associação de colunas','Ao ler a Bíblia, tem um encontro pessoal com o Senhor','A - Neo-Ortodoxa | B - Conservadora','A','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.15','Associação de colunas','Barth','A - Neo-Ortodoxa | B - Conservadora','A','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.16','Associação de colunas','A Bíblia é soberana','A - Neo-Ortodoxa | B - Conservadora','B','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.17','Certo/Errado','Os cristãos primitivos tinham os patriarcas hebreus como oráculos de Deus.','C/E','E','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.18','Certo/Errado','Marcião de Sinope propôs seu sistema teológico chamado marcionismo.','C/E','C','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.19','Certo/Errado','Martinho Lutero afirmou que a Bíblia Sagrada é a nossa única regra em matéria de fé e prática.','C/E','C','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',2,'2.20','Certo/Errado','A comunidade de fé pentecostal acredita ser a Bíblia a inspirada, inerrante, infalível e completa Palavra de Deus.','C/E','C','BIBLIOLOGIA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',3,'3.1','Preencher lacuna','A Bíblia Sagrada é um livro de ______ autoria.','(lacuna)','dupla','BIBLIOLOGIA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',3,'3.2','Preencher lacuna','A revelação e registro das Escrituras Sagradas compreende um período de aproximadamente ______ anos.','(lacuna)','1.600','BIBLIOLOGIA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',3,'3.3','Preencher lacuna','A Palavra de Deus é ______ só.','(lacuna)','uma','BIBLIOLOGIA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',3,'3.4','Preencher lacuna','O Espírito Santo inspirou e capacitou cerca de ______ diferentes autores da Bíblia.','(lacuna)','quarenta','BIBLIOLOGIA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',3,'3.5','Certo/Errado','As confissões de fé mais antigas e idôneas afirmam categoricamente que a Bíblia é a inspirada, inerrante, infalível, soberana e completa Palavra de Deus.','C/E','C','BIBLIOLOGIA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',3,'3.6','Certo/Errado','A canonicidade dos livros da Bíblia repousa sobre o assentimento intelectual dos pais da igreja.','C/E','E','BIBLIOLOGIA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',3,'3.7','Certo/Errado','A inspiração da Bíblia independe da aprovação humana.','C/E','C','BIBLIOLOGIA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',3,'3.8','Certo/Errado','A canonização significa "tornar divino".','C/E','E','BIBLIOLOGIA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',3,'3.9','Associação de colunas','norma, regra','A - exame textual | B - autor sagrado | C - Cânon','C','BIBLIOLOGIA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',3,'3.10','Associação de colunas','rabinos judeus e teólogos cristãos','A - exame textual | B - autor sagrado | C - Cânon','A','BIBLIOLOGIA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',3,'3.11','Associação de colunas','escreveu o texto','A - exame textual | B - autor sagrado | C - Cânon','B','BIBLIOLOGIA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',3,'3.12','Certo/Errado','Os livros do Antigo Testamento sempre estiveram em disputa na antiga comunidade de Israel.','C/E','E','BIBLIOLOGIA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',3,'3.13','Certo/Errado','De acordo com as tradições preservadas na Mishná, dois conselhos de rabinos judeus foram realizados.','C/E','C','BIBLIOLOGIA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',3,'3.14','Certo/Errado','Foi rápido para que se chegasse à definição do cânon que conhecemos hoje.','C/E','E','BIBLIOLOGIA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',3,'3.15','Certo/Errado','Tanto o Antigo quanto o Novo Testamento são comprovadamente de origem divina; foram inspirados pelo Espírito Santo.','C/E','C','BIBLIOLOGIA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.1','Certo/Errado','A palavra "inspiração divina" literalmente, significa: "aquilo que é dado pelo sopro de Deus".','C/E','C','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.2','Certo/Errado','A ação natural do Espírito Santo sobre os escritores sagrados, que os levou a produzir a Palavra de Deus.','C/E','E','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.3','Certo/Errado','A palavra "inspirar" é "introduzir ar nos pulmões".','C/E','C','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.4','Certo/Errado','A Bíblia Sagrada foi escrita de maneira sobrenatural, inerrante, infalível e singular pela ação do Espirito Santo.','C/E','C','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.5','Associação de colunas','Partes da Bíblia são inspiradas, outras não.','A - Inspiração Natural Humana | B - Inspiração Divina Comum | C - Inspiração Parcial','C','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.6','Associação de colunas','Escrita por gênios','A - Inspiração Natural Humana | B - Inspiração Divina Comum | C - Inspiração Parcial','A','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.7','Associação de colunas','A inspiração é a mesma de quando oramos.','A - Inspiração Natural Humana | B - Inspiração Divina Comum | C - Inspiração Parcial','B','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.8','Associação de colunas','Inspirou as ideias e não as palavras.','A - Ditado Verbal | B - Inspiração das Ideias | C - Inspiração Plenária','B','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.9','Associação de colunas','Toda a Bíblia foi inspirada.','A - Ditado Verbal | B - Inspiração das Ideias | C - Inspiração Plenária','C','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.10','Associação de colunas','Ditados mecanicamente.','A - Ditado Verbal | B - Inspiração das Ideias | C - Inspiração Plenária','A','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.11','Certo/Errado','Revelação é a ação de Deus pela qual Ele dá a conhecer ao escritor coisas já conhecidas.','C/E','E','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.12','Certo/Errado','A inspiração nem sempre implica em revelação.','C/E','C','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.13','Certo/Errado','Toda a Bíblia foi inspirada por Deus, e toda ela foi dada por revelação.','C/E','E','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.14','Certo/Errado','O capítulo 15 de 1 Coríntios fala a respeito da ressurreição de Cristo.','C/E','C','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.15','Preencher lacuna','A Bíblia é o único livro capaz de ______ o indivíduo.','(lacuna)','regenerar','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.16','Preencher lacuna','A cultura ocidental foi diretamente ______ pelas Escrituras em sua formatação.','(lacuna)','influenciada','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',4,'4.17','Preencher lacuna','A existência da Bíblia Sagrada figura como ______ para a humanidade.','(lacuna)','luzeiro','BIBLIOLOGIA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.1','Certo/Errado','A palavra "inerrância" significa, literalmente, que não comete erros; infalível.','C/E','C','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.2','Certo/Errado','Teologicamente a inerrância bíblica é a doutrina segundo a qual as Sagradas Escrituras contêm alguns erros.','C/E','E','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.3','Certo/Errado','A Bíblia jamais errou ao nos informar acerca dos propósitos e vindicações divinas nela apresentados.','C/E','C','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.4','Certo/Errado','A inerrância requer infalibilidade, mas a infalibilidade não requer inerrância.','C/E','E','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.5','Múltipla escolha','A maior razão do debate teológico do Século XX foi em torno da','a. filosofia bíblica | b. doutrina bíblica | c. inerrância bíblica | d. Nenhuma das alternativas é correta','c','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.6','Múltipla escolha','Os filósofos seculares começaram a por dúvidas sobre a integridade da Bíblia a partir do','a. modernismo | b. iluminismo | c. renascimento | d. Todas as alternativas estão corretas','b','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.7','Múltipla escolha','A discussão sobre a inerrância da Bíblia se acirrou com a','a. teologia pentecostal | b. teologia convencional | c. teologia ortodoxa | d. Nenhuma das alternativas é correta','d','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.8','Múltipla escolha','Documento originado pela ortodoxia cristã em defesa da inerrância bíblica','a. Declaração de Boston | b. Declaração de Chicago | c. Declaração de Washington | d. Nenhuma das alternativas é correta','b','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.9','Preencher lacuna','Em 1978, foi realizada a Conferência Internacional sobre Inerrância Bíblica na cidade norte-americana de ______.','(lacuna)','Chicago','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.10','Preencher lacuna','Os cinco primeiros artigos da Declaração de Chicago sintetizam a fé ortodoxa concernente à ______ da Bíblia Sagrada.','(lacuna)','inerrância','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.11','Preencher lacuna','Sendo total e plenariamente dadas pelo próprio Deus, as ______ estão isentas de erros.','(lacuna)','Escrituras','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.12','Preencher lacuna','A autoridade das Escrituras será fatalmente ______ se a sua absoluta inerrância for, de alguma forma, menosprezada.','(lacuna)','enfraquecida','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.13','Certo/Errado','A doutrina da inerrância bíblica não é contraditória nem fere a razão.','C/E','C','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.14','Certo/Errado','A Bíblia Sagrada, como a inspirada e inerrante Palavra de Deus, vai de encontro à verdadeira filosofia.','C/E','E','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.15','Certo/Errado','Não há quaisquer erros científicos na Bíblia.','C/E','C','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.16','Certo/Errado','A arqueologia vem sendo largamente utilizada para deturpar quão firme é a doutrina da inerrância bíblica.','C/E','E','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.17','Sublinhar (escolha da palavra correta)','A Bíblia é (filosoficamente, historicamente) precisa.','filosoficamente | historicamente','historicamente','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.18','Sublinhar (escolha da palavra correta)','Lendo a Bíblia com sinceridade convencemo-nos que ela é, de fato, a inspirada e (absoluta, inerrante) Palavra de Deus.','absoluta | inerrante','inerrante','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.19','Sublinhar (escolha da palavra correta)','Nenhuma profecia da Escritura é de (particular, geral) interpretação.','particular | geral','particular','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.20','Associação de colunas','Importância normativa','A - Gegraptai | B - Talogia | C - Graphe','C','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.21','Associação de colunas','Está escrito','A - Gegraptai | B - Talogia | C - Graphe','A','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.22','Associação de colunas','Oráculos de Deus','A - Gegraptai | B - Talogia | C - Graphe','B','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.23','Associação de colunas','Em parte alguma pode haver falsidade...','A - Martinho Lutero | B - Agostinho | C - Tomás de Aquino | D - Charles Spurgeon','C','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.24','Associação de colunas','Creio firmemente...','A - Martinho Lutero | B - Agostinho | C - Tomás de Aquino | D - Charles Spurgeon','B','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.25','Associação de colunas','Aprendi a atribuir infalibilidade...','A - Martinho Lutero | B - Agostinho | C - Tomás de Aquino | D - Charles Spurgeon','A','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',5,'5.26','Associação de colunas','Uma pena que nunca borra...','A - Martinho Lutero | B - Agostinho | C - Tomás de Aquino | D - Charles Spurgeon','D','BIBLIOLOGIA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',6,'6.1','Certo/Errado','Infalibilidade é a característica do que é infalível, do que não falha.','C/E','C','BIBLIOLOGIA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',6,'6.2','Certo/Errado','A inerrância da Palavra de Deus ensina ser a Bíblia infalível em tudo o que diz.','C/E','C','BIBLIOLOGIA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',6,'6.3','Certo/Errado','Muitas são as passagens que atestam a infalibilidade das Sagradas Escrituras.','C/E','C','BIBLIOLOGIA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',6,'6.4','Certo/Errado','No Brasil, não se lançam suspeições sobre a infalibilidade das Sagradas Escrituras.','C/E','E','BIBLIOLOGIA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',6,'6.5','Certo/Errado','Na obra de Nostradamus, qualquer interpretação é possível.','C/E','C','BIBLIOLOGIA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',6,'6.6','Certo/Errado','A Bíblia não é clara e cristalinamente simples.','C/E','E','BIBLIOLOGIA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',6,'6.7','Certo/Errado','A clareza das Escrituras é uma das doutrinas mais admiráveis da Palavra do Senhor.','C/E','C','BIBLIOLOGIA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',6,'6.8','Certo/Errado','Deus se comunica conosco em nossa linguagem.','C/E','C','BIBLIOLOGIA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',6,'6.9','Múltipla escolha','Clareza é qualidade do que é claro, inteligível e perfeitamente','a. limpo | b. colocado | c. compreensível | d. Nenhuma das alternativas é correta','c','BIBLIOLOGIA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',6,'6.10','Múltipla escolha','A clareza é conhecida também como','a. pureza | b. perspicuidade | c. inteligível | d. Todas as alternativas estão corretas','b','BIBLIOLOGIA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',6,'6.11','Múltipla escolha','A Bíblia testemunha quanto a sua','a. clareza | b. pureza | c. compreenção | d. Todas as alternativas estão corretas','a','BIBLIOLOGIA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',7,'7.1','Certo/Errado','A autoridade da Bíblia é questionável.','C/E','E','BIBLIOLOGIA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',7,'7.2','Certo/Errado','A Bíblia não conhece limites; é suprema em matéria de fé e prática.','C/E','C','BIBLIOLOGIA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',7,'7.3','Certo/Errado','Israel acatava parcialmente a autoridade das Sagradas Escrituras.','C/E','E','BIBLIOLOGIA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',7,'7.4','Certo/Errado','A autoridade da Bíblia advém-lhe do fato de ela ser a inspirada, inerrante e infalível Palavra de Deus.','C/E','C','BIBLIOLOGIA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',7,'7.5','Múltipla escolha','A Reforma Protestante resgatou, no seio da cristandade','a. a supremacia da Bíblia | b. o temor a Deus | c. a liberdade de expressão | d. Nenhuma das alternativas é correta','a','BIBLIOLOGIA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',7,'7.6','Múltipla escolha','A Igreja Católica Romana colocava acima das Sagradas Escrituras','a. papado | b. tradição | c. indulgências | d. Todas as alternativas estão corretas','b','BIBLIOLOGIA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',7,'7.7','Múltipla escolha','Criados para os que ousavam pensar diferentemente da hierarquia romana','a. as Cruzadas | b. o Tribunal da Inquisição | c. as perseguições | d. Todas as alternativas estão corretas','d','BIBLIOLOGIA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',7,'7.8','Múltipla escolha','Os reformadores recolocaram as Sagradas Escrituras no lugar onde elas sempre deveriam estar','a. no púlpito da igreja | b. no banco da igreja | c. no centro da igreja | d. Nenhuma das alternativas é correta','c','BIBLIOLOGIA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',7,'7.9','Certo/Errado','Características absolutas acerca das Escrituras Sagradas: sua autoridade e completude.','C/E','C','BIBLIOLOGIA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',7,'7.10','Certo/Errado','Completude é qualidade, estado ou propriedade do que é completo, perfeito, acabado.','C/E','C','BIBLIOLOGIA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',7,'7.11','Certo/Errado','A Bíblia é completa em si mesma.','C/E','C','BIBLIOLOGIA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',7,'7.12','Certo/Errado','O seu cânon foi encerrado na revelação dada a João.','C/E','C','BIBLIOLOGIA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',7,'7.13','Certo/Errado','A Bíblia, pois, necessita de acréscimos.','C/E','E','BIBLIOLOGIA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',7,'7.14','Certo/Errado','Afirma o apóstolo João que consideremos anátema a quem anunciar outro Evangelho.','C/E','E','BIBLIOLOGIA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.1','Certo/Errado','Hank Hanegraaff, utilizou a palavra site, em inglês, e mostra como devemos interpretar as Sagradas Escrituras.','C/E','E','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.2','Certo/Errado','Quando nos depararmos como uma parábola, ou com uma metáfora, interpretemo-las de acordo com o método literal.','C/E','E','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.3','Certo/Errado','Na interpretação da Bíblia, podemos contar com iluminação do Espirito Santo.','C/E','C','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.4','Certo/Errado','A exposição da Palavra de Deus dá-nos luz.','C/E','C','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.5','Associação de colunas','Poéticos','A - Mateus 19:24 | B - João 21:25 | C - Gálatas 4 | D - Salmos 36:7 | E - Jó 41:1 | F - Jó, Salmos... | G - Gênesis 6:6 | H - Evangelhos sinóticos','F','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.6','Associação de colunas','Parábolas','A - Mateus 19:24 | B - João 21:25 | C - Gálatas 4 | D - Salmos 36:7 | E - Jó 41:1 | F - Jó, Salmos... | G - Gênesis 6:6 | H - Evangelhos sinóticos','H','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.7','Associação de colunas','Alegorias','A - Mateus 19:24 | B - João 21:25 | C - Gálatas 4 | D - Salmos 36:7 | E - Jó 41:1 | F - Jó, Salmos... | G - Gênesis 6:6 | H - Evangelhos sinóticos','C','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.8','Associação de colunas','Metáforas','A - Mateus 19:24 | B - João 21:25 | C - Gálatas 4 | D - Salmos 36:7 | E - Jó 41:1 | F - Jó, Salmos... | G - Gênesis 6:6 | H - Evangelhos sinóticos','G','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.9','Associação de colunas','Comparações','A - Mateus 19:24 | B - João 21:25 | C - Gálatas 4 | D - Salmos 36:7 | E - Jó 41:1 | F - Jó, Salmos... | G - Gênesis 6:6 | H - Evangelhos sinóticos','B','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.10','Associação de colunas','Figuras poéticas','A - Mateus 19:24 | B - João 21:25 | C - Gálatas 4 | D - Salmos 36:7 | E - Jó 41:1 | F - Jó, Salmos... | G - Gênesis 6:6 | H - Evangelhos sinóticos','E','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.11','Associação de colunas','Sátiras','A - Mateus 19:24 | B - João 21:25 | C - Gálatas 4 | D - Salmos 36:7 | E - Jó 41:1 | F - Jó, Salmos... | G - Gênesis 6:6 | H - Evangelhos sinóticos','A','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.12','Associação de colunas','Figuras de Linguagem','A - Mateus 19:24 | B - João 21:25 | C - Gálatas 4 | D - Salmos 36:7 | E - Jó 41:1 | F - Jó, Salmos... | G - Gênesis 6:6 | H - Evangelhos sinóticos','D','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.13','Associação de colunas','Legislador','A - Salomão | B - Daniel | C - Samuel | D - Lucas | E - Moisés','E','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.14','Associação de colunas','Profetas','A - Salomão | B - Daniel | C - Samuel | D - Lucas | E - Moisés','C','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.15','Associação de colunas','Reis','A - Salomão | B - Daniel | C - Samuel | D - Lucas | E - Moisés','A','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.16','Associação de colunas','Estadista','A - Salomão | B - Daniel | C - Samuel | D - Lucas | E - Moisés','B','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.17','Associação de colunas','Médico','A - Salomão | B - Daniel | C - Samuel | D - Lucas | E - Moisés','D','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.18','Múltipla escolha','O ensino teológico é imprescindível na interpretação da','a. Bíblia | b. Palavra de Deus | c. Sagradas Escrituras | d. Todas as alternativas estão corretas','d','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.19','Múltipla escolha','A Bíblia interpreta a','a. História | b. Bíblia | c. Deus | d. Todas as alternativas estão corretas','b','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.20','Certo/Errado','Como filhos de Deus, não podemos nos afastar jamais das Sagradas Escrituras.','C/E','C','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.21','Certo/Errado','Quanto mais lermos a Bíblia, mais íntimos seremos de seu Autor.','C/E','C','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.22','Certo/Errado','Tanto na igreja de Cristo como em nossa vida a Bíblia deve ocupar sempre o primeiro lugar.','C/E','C','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Bibliologia',8,'8.23','Certo/Errado','Se de fato somos escolhidos de Deus, temos de ser identificados com o Livro de Deus.','C/E','C','BIBLIOLOGIA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.1','Certo/Errado','Um pregador é um cristão exatamente como qualquer outro.','C/E','C','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.2','Certo/Errado','Um chamamento geralmente começa na forma de algo inconsciente no espírito de um homem.','C/E','E','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.3','Certo/Errado','Ficamos absolutamente certos do chamado para o ministério da pregação quando somos incapazes de mantê-lo à distância e de resistir-lhe.','C/E','C','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.4','Certo/Errado','A verdade parece ser que quanto maior o pregador, mais confiante ele se tem mostrado em começar a pregar.','C/E','E','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.5','Associação de colunas','atitudes e palavras','A - SERIEDADE | B - SINCERIDADE | C - HONESTIDADE','C','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.6','Associação de colunas','atitude reverente','A - SERIEDADE | B - SINCERIDADE | C - HONESTIDADE','A','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.7','Associação de colunas','é ser realista','A - SERIEDADE | B - SINCERIDADE | C - HONESTIDADE','B','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.8','Sublinhar (escolha da palavra correta)','A palavra piedade vem do latim pietate e significa amor e (respeito, dedicação) pelas coisas sagradas.','respeito | dedicação','respeito','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.9','Sublinhar (escolha da palavra correta)','O obreiro que ministra a palavra deve estudar a Bíblia (sistematicamente, regularmente).','sistematicamente | regularmente','sistematicamente','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.10','Sublinhar (escolha da palavra correta)','A (meditação, oração) inspira a mensagem ao pregador e capacita-o a transmitir à igreja.','meditação | oração','oração','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.11','Sublinhar (escolha da palavra correta)','O pregador tem que (ensinar, aprender) que é pó e cinza, que nada sabe, que nada pode fazer sem o Senhor Jesus.','ensinar | aprender','aprender','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.12','Preencher lacuna','O sermão faz parte do ______ de Deus, vindo daí sua notável e extraordinária longevidade.','(lacuna)','mandamento','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.13','Preencher lacuna','Deus nos criou com capacidade de ______, ______ e ______.','(lacuna) x3','pensar, ouvir e falar','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.14','Preencher lacuna','No livro de ______ encontramos o relato de que Esdras lia o livro da Lei em voz alta para as pessoas.','(lacuna)','Neemias','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.15','Preencher lacuna','O livro de ______ mostra o apóstolo pregando em diferentes cenários.','(lacuna)','Atos','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.16','Múltipla escolha','Os sermões de Basílio estavam repletos de','a. exortações e parábolas | b. exortações e exemplos práticos | c. consolo e exemplos práticos | d. Nenhuma das alternativas é correta','b','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.17','Múltipla escolha','João Calvino não era forte no emprego de','a. metáforas | b. exortações | c. profecias | d. Todas as alternativas estão corretas','a','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.18','Múltipla escolha','Edwards enfatizou a alta visão calvinista da soberania de Deus','a. na salvação do homem | b. na perdição do homem | c. na escatologia bíblica | d. Nenhuma das alternativas é correta','a','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',1,'1.19','Múltipla escolha','A história da igreja destaca, em todas as eras, quanto são enormes e angustiantes os riscos de','a. jejuar | b. orar | c. pregar | d. Todas as alternativas estão corretas','c','HOMILETICA.pdf L1 + GABARITO EXERCICIOS.pdf'),
('Homilética',2,'2.1','Certo/Errado','Os grandes pregadores do Novo Testamento usaram as Escrituras como autoridade única para o embasamento de suas mensagens.','C/E','C','HOMILETICA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Homilética',2,'2.2','Certo/Errado','Jesus, baseado no livro do profeta Isaías capítulo 61 pregou seu primeiro sermão público na sinagoga.','C/E','C','HOMILETICA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Homilética',2,'2.3','Certo/Errado','De Estêvão, o pregador que morreu pregando, ficaram registradas duas prédicas, que custaram sua própria vida.','C/E','E','HOMILETICA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Homilética',2,'2.4','Certo/Errado','Uma das maiores necessidades da igreja atual é ter uma pregação verdadeiramente bíblica.','C/E','C','HOMILETICA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Homilética',2,'2.5','Sublinhar (escolha da palavra correta)','Escolha textos (obscuros, claros) para você mesmo, bem como para os seus ouvintes.','obscuros | claros','claros','HOMILETICA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Homilética',2,'2.6','Sublinhar (escolha da palavra correta)','Escolha textos dentro dos limites de sua (capacidade, vocação).','capacidade | vocação','capacidade','HOMILETICA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Homilética',2,'2.7','Sublinhar (escolha da palavra correta)','Antes que você tenha que convencer os seus ouvintes de uma verdade, esteja absolutamente certo que ela lhe (falou, convenceu) primeiro.','falou | convenceu','convenceu','HOMILETICA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Homilética',2,'2.8','Sublinhar (escolha da palavra correta)','Escolha textos que apelem à (memoria, imaginação) dos ouvintes.','memoria | imaginação','imaginação','HOMILETICA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Homilética',2,'2.9','Associação de colunas','examinar o que precede','A - Fiel e Corretamente | B - Recorrer ao contexto | C - Escritura pela Escritura','B','HOMILETICA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Homilética',2,'2.10','Associação de colunas','a Bíblia interpreta a Bíblia','A - Fiel e Corretamente | B - Recorrer ao contexto | C - Escritura pela Escritura','C','HOMILETICA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Homilética',2,'2.11','Associação de colunas','sentido literal ou figurado','A - Fiel e Corretamente | B - Recorrer ao contexto | C - Escritura pela Escritura','A','HOMILETICA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Homilética',2,'2.12','Certo/Errado','Não é preciso um conhecimento do significado do texto quando ele foi escrito para uma interpretação correta.','C/E','E','HOMILETICA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Homilética',2,'2.13','Certo/Errado','Nenhum texto deve chocar-se com o ensino geral da Bíblia.','C/E','C','HOMILETICA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Homilética',2,'2.14','Certo/Errado','A Bíblia deve ser pregada apenas no sentido histórico.','C/E','E','HOMILETICA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Homilética',2,'2.15','Certo/Errado','Não se precipite em interpretar as Escrituras de qualquer maneira.','C/E','C','HOMILETICA.pdf L2 + GABARITO EXERCICIOS.pdf'),
('Homilética',3,'3.1','Certo/Errado','A forma Retórica de tema é aquela que implica na apresentação de um pensamento completo, mas de modo resumido.','C/E','E','HOMILETICA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Homilética',3,'3.2','Certo/Errado','A Forma Lógica de tema é o tema objetivo.','C/E','E','HOMILETICA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Homilética',3,'3.3','Certo/Errado','O tema múltiplo, ou seja, o generalizado, do qual se podem extrair outros temas deve ser evitado.','C/E','C','HOMILETICA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Homilética',3,'3.4','Certo/Errado','O que mantém a unidade do sermão é o rumo dado ao mesmo.','C/E','C','HOMILETICA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Homilética',3,'3.5','Sublinhar (escolha da palavra correta)','O tema (enfático, interrogativo) é aquele que aparece sob a forma de uma palavra ou de uma frase.','enfático | interrogativo','enfático','HOMILETICA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Homilética',3,'3.6','Sublinhar (escolha da palavra correta)','No tema interrogativo o sermão será desenvolvido na base de (negação, contestação) à pergunta feita.','negação | contestação','contestação','HOMILETICA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Homilética',3,'3.7','Sublinhar (escolha da palavra correta)','O tema declarativo se preocupa em desenvolver o significado e a (comprovação, valorização) da declaração.','comprovação | valorização','comprovação','HOMILETICA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Homilética',3,'3.8','Certo/Errado','O tema imperativo é encontrado na Bíblia em forma de mandamento ou ordem divina.','C/E','C','HOMILETICA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Homilética',3,'3.9','Certo/Errado','O tema biográfico ou histórico coloca em destaque algum fato importante da vida de uma personagem.','C/E','C','HOMILETICA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Homilética',3,'3.10','Associação de colunas','Energia divina','A - Tema objetivo | B - Tema vital | C - Tema pertinente | D - Tema contextualizado | E - Tema breve','B','HOMILETICA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Homilética',3,'3.11','Associação de colunas','Único no sermão','A - Tema objetivo | B - Tema vital | C - Tema pertinente | D - Tema contextualizado | E - Tema breve','C','HOMILETICA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Homilética',3,'3.12','Associação de colunas','Dirigido a um alvo','A - Tema objetivo | B - Tema vital | C - Tema pertinente | D - Tema contextualizado | E - Tema breve','A','HOMILETICA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Homilética',3,'3.13','Associação de colunas','Resumo da verdade','A - Tema objetivo | B - Tema vital | C - Tema pertinente | D - Tema contextualizado | E - Tema breve','E','HOMILETICA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Homilética',3,'3.14','Associação de colunas','Elo com o momento','A - Tema objetivo | B - Tema vital | C - Tema pertinente | D - Tema contextualizado | E - Tema breve','D','HOMILETICA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Homilética',3,'3.15','Múltipla escolha','Requisitos Importantes para a Escolha de Temas','a. Fuja de temas triviais e frívolos | b. Defina-se por temas que produzam bênçãos | c. Escolha temas apropriados para a época, lugar e ocasião | d. Todas as alternativas estão corretas','d','HOMILETICA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Homilética',3,'3.16','Múltipla escolha','Não é uma vantagens de um Bom Tema','a. Desperta a atenção do ouvinte | b. Valoriza a mensagem | c. Trazer temor a quem ouve | d. Nenhuma das alternativas é correta','c','HOMILETICA.pdf L3 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.1','Certo/Errado','A introdução é a parte inicial da mensagem, o ponto de contato entre o pregador e o auditório.','C/E','C','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.2','Certo/Errado','Tecnicamente a introdução deve ocupar uma terça parte do discurso.','C/E','E','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.3','Certo/Errado','É na introdução que o pregador conquistará ou perderá a atenção do seu auditório.','C/E','C','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.4','Certo/Errado','Para alcançar os ouvintes, o sermão nem sempre precisa de base bíblica e identificação com os ouvintes.','C/E','E','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.5','Associação de colunas','Letra de um hino','A - Afirmação | B - Interrogação | C - Música | D - Poética','C','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.6','Associação de colunas','Exelente recurso','A - Afirmação | B - Interrogação | C - Música | D - Poética','D','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.7','Associação de colunas','Bem formulada','A - Afirmação | B - Interrogação | C - Música | D - Poética','B','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.8','Associação de colunas','Ser atraente, clara','A - Afirmação | B - Interrogação | C - Música | D - Poética','A','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.9','Sublinhar (escolha da palavra correta)','O plano é a parte (secundaria, principal) do sermão.','secundaria | principal','principal','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.10','Sublinhar (escolha da palavra correta)','Um sermão bem elaborado é (apresentado, colocado) com ideias organizadas e disposto ordenadamente.','apresentado | colocado','apresentado','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.11','Sublinhar (escolha da palavra correta)','A harmonia das divisões de um sermão está no fato de que, seus pontos principais ainda que (próximos, distintos) uns dos outros, se relacionam devidamente.','próximos | distintos','distintos','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.12','Sublinhar (escolha da palavra correta)','(Transição, Pertinência) é a passagem de um ponto para o outro ou de uma divisão para a outra.','Transição | Pertinência','Transição','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.13','Certo/Errado','Na ordem lógica, nem sempre as divisões devem ser de natureza crescente.','C/E','E','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.14','Certo/Errado','Na ordem lógica, se o sermão é doutrinário, as divisões devem seguir a ordem doutrinária.','C/E','C','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.15','Certo/Errado','Na divisão cronológica, as divisões principais são indicadas por algarismos romanos.','C/E','C','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.16','Certo/Errado','Na divisão cronológica a ordem cronológica é geralmente desdobrada de cinco modos.','C/E','E','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.17','Preencher lacuna','A quantidade de pontos e ______ do sermão são determinadas pela natureza do tema ou o conteúdo do texto bíblico.','(lacuna)','subpontos','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.18','Preencher lacuna','O sermão nunca deve ter menos do que ______ divisões.','(lacuna)','duas','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.19','Preencher lacuna','As subdivisões ou subpontos são os ______ explicativos das divisões principais.','(lacuna)','detalhes','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.20','Preencher lacuna','Podemos chamar as ______ de pontos auxiliares dos pontos principais.','(lacuna)','subdivisões','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.21','Múltipla escolha','Em muitos sermões parece que o pregador perde','a. a harmonia | b. a unção | c. o rumo | d. Nenhuma das alternativas é correta','c','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.22','Múltipla escolha','Encerrar no momento certo o sermão é uma das grandes habilidades que o pregador deve','a. desenvolver | b. usar | c. observar | d. Todas as alternativas estão corretas','a','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.23','Múltipla escolha','Conclusões longas dificilmente alcançam','a. a verdade | b. o propósito | c. o interesse | d. Nenhuma das alternativas é correta','b','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',4,'4.24','Múltipla escolha','O apelo é parte importante do sermão, não é','a. apêndice, outra mensagem | b. outra mensagem, oportunidade | c. oportunidade, apêncide | d. Todas as alternativas estão corretas','a','HOMILETICA.pdf L4 + GABARITO EXERCICIOS.pdf'),
('Homilética',5,'5.1','Certo/Errado','Sermões Temáticos são aqueles cujas divisões são tiradas do tema, independente do texto.','C/E','C','HOMILETICA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Homilética',5,'5.2','Certo/Errado','No sermão temático a divisão do sermão se prende ao texto bíblico.','C/E','E','HOMILETICA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Homilética',5,'5.3','Certo/Errado','Sermão textual é aqueles cuja divisão se baseia obrigatoriamente no tema bíblico.','C/E','E','HOMILETICA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Homilética',5,'5.4','Certo/Errado','Divisão textual natural é o tipo de divisão que usa as palavras do próprio tema bíblico escolhido.','C/E','E','HOMILETICA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Homilética',5,'5.5','Certo/Errado','Divisão textual analítica é o tipo de divisão que colhe a ideia geral que o texto bíblico fornece.','C/E','C','HOMILETICA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Homilética',5,'5.6','Certo/Errado','Divisão textual sintética é o tipo de divisão que resume as partes principais do texto.','C/E','C','HOMILETICA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Homilética',5,'5.7','Preencher lacuna','O Sermão expositivo tem por função tornar claro o texto bíblico, expondo o conteúdo ______ que o texto encerra.','(lacuna)','exegético','HOMILETICA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Homilética',5,'5.8','Preencher lacuna','A ______ sermão expositivo é feita de forma lógica e cronológica.','(lacuna)','divisão','HOMILETICA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Homilética',5,'5.9','Preencher lacuna','A pregação expositiva extrai tanto os pontos ______ quanto os secundários.','(lacuna)','principais','HOMILETICA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Homilética',5,'5.10','Preencher lacuna','Uma das maiores necessidades da ______ atual é ter uma pregação verdadeiramente bíblica.','(lacuna)','igreja','HOMILETICA.pdf L5 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.1','Múltipla escolha','As formas de preparação e comunicação do sermão','a. Escrever e ler o sermão | b. Escrever, memorizar e recitar | c. Escrever apenas o esboço | d. Todas as alternativas estão corretas','d','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.2','Múltipla escolha','Ajuda a conservar melhor a unidade do sermão','a. Escrever e ler o sermão | b. Escrever, memorizar e recitar | c. Escrever apenas o esboço | d. Todas as alternativas estão corretas','a','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.3','Múltipla escolha','Deixa o pregador livre para gesticular','a. Escrever e ler o sermão | b. Escrever, memorizar e recitar | c. Escrever apenas o esboço | d. Nenhuma das alternativas é correta','b','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.4','Múltipla escolha','Alguns pregadores ao invés de escrever o sermão todo, apenas','a. fazem anotações | b. fazem texto | c. fazem esboço | d. Todas as alternativas estão corretas','c','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.5','Certo/Errado','A eloquência é o dom natural da palavra, ou seja, é nata da pessoa, ela já nasce com esse dom.','C/E','C','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.6','Certo/Errado','É a eloquência a arte de falar com propriedade em função do discurso.','C/E','C','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.7','Certo/Errado','É eloquência o discurso em que o emprego das palavras nem sempre atinge ao fim desejado.','C/E','E','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.8','Certo/Errado','A eloquência é caracterizada pelo uso da palavra clara, precisa, perfeitamente ajustada à melhor expressão do momento.','C/E','E','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.9','Associação de colunas','tirar, extrair','A - A priori | B - A posteriori | C - Por Analogia | D - Por Dilema | E - Por Dedução | F - Por Refutação','E','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.10','Associação de colunas','contestação','A - A priori | B - A posteriori | C - Por Analogia | D - Por Dilema | E - Por Dedução | F - Por Refutação','F','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.11','Associação de colunas','Mateus o registra usado por Jesus','A - A priori | B - A posteriori | C - Por Analogia | D - Por Dilema | E - Por Dedução | F - Por Refutação','D','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.12','Associação de colunas','do efeito para a causa','A - A priori | B - A posteriori | C - Por Analogia | D - Por Dilema | E - Por Dedução | F - Por Refutação','B','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.13','Associação de colunas','das causas para os efeitos','A - A priori | B - A posteriori | C - Por Analogia | D - Por Dilema | E - Por Dedução | F - Por Refutação','A','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.14','Associação de colunas','é a força que atua','A - A priori | B - A posteriori | C - Por Analogia | D - Por Dilema | E - Por Dedução | F - Por Refutação','C','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.15','Sublinhar (escolha da palavra correta)','Um dos principais problemas do sermão (rápido, moroso) é a falta de movimento.','rápido | moroso','moroso','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.16','Sublinhar (escolha da palavra correta)','O movimento também implica no passo (correto, normal) para cobrir toda a matéria do sermão.','correto | normal','correto','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.17','Sublinhar (escolha da palavra correta)','É preciso haver momentos de (pequena, grande) intensidade e, em seguida, um retorno aos momentos de descanso para a congregação.','pequena | grande','grande','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.18','Sublinhar (escolha da palavra correta)','Numa situação ideal, o padrão de um sermão pode ser definido como (harmônico, sinfônico).','harmônico | sinfônico','sinfônico','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.19','Certo/Errado','Os antigos romanos tinham mais consciência da natureza do discurso persuasivo do que talvez qualquer outro povo.','C/E','E','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.20','Certo/Errado','A retórica de Diostenes assume a posição de que "o estudo retórico, em seu exato sentido, se preocupa com os modos de persuasão".','C/E','E','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.21','Certo/Errado','A pregação apostólica sempre foi orientada para levar a uma decisão.','C/E','C','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.22','Certo/Errado','O ministério fiel do Espírito Santo, que convence o mundo do pecado, da justiça e do juízo, continua hoje e vai perdurar até a volta de Jesus.','C/E','C','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.23','Associação de colunas','mãos abertas, palmas para cima','A - Repelir | B - Gesto de aceitação | C - Gesto de aguardar | D - Desprezo','B','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.24','Associação de colunas','cruza-se os braços','A - Repelir | B - Gesto de aceitação | C - Gesto de aguardar | D - Desprezo','C','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.25','Associação de colunas','recuar um pouco o peito','A - Repelir | B - Gesto de aceitação | C - Gesto de aguardar | D - Desprezo','A','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.26','Associação de colunas','olhar oblíquo','A - Repelir | B - Gesto de aceitação | C - Gesto de aguardar | D - Desprezo','D','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.27','Preencher lacuna','Se o pregador quer que sua mensagem tenha efeito, olhe de ______ a seu auditório.','(lacuna)','frente','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.28','Preencher lacuna','O orador deve evitar pôr as ______ nos quadris, e enfiá-las no bolso ou cruzá-las.','(lacuna)','mãos','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.29','Preencher lacuna','O orador deve evitar os ______ rápidos, nervosos, frequentes e mecânicos.','(lacuna)','gestos','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',6,'6.30','Preencher lacuna','O orador quando se ergue para falar, não o deve fazer como alguém ______.','(lacuna)','cansado','HOMILETICA.pdf L6 + GABARITO EXERCICIOS.pdf'),
('Homilética',7,'7.1','Associação de colunas','sua voz sobe e desce','A - Resmungador | B - Gritador | C - Cantarolador | D - Monótono | E - Pigarreador','C','HOMILETICA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Homilética',7,'7.2','Associação de colunas','procura limpar a garganta','A - Resmungador | B - Gritador | C - Cantarolador | D - Monótono | E - Pigarreador','E','HOMILETICA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Homilética',7,'7.3','Associação de colunas','fala com os lábios','A - Resmungador | B - Gritador | C - Cantarolador | D - Monótono | E - Pigarreador','A','HOMILETICA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Homilética',7,'7.4','Associação de colunas','uma só tonalidade','A - Resmungador | B - Gritador | C - Cantarolador | D - Monótono | E - Pigarreador','D','HOMILETICA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Homilética',7,'7.5','Associação de colunas','voz estridente','A - Resmungador | B - Gritador | C - Cantarolador | D - Monótono | E - Pigarreador','B','HOMILETICA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Homilética',7,'7.6','Certo/Errado','O pregador deve ouvir sua própria voz e emiti-la com cuidado.','C/E','C','HOMILETICA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Homilética',7,'7.7','Certo/Errado','Boa fluidez na voz equivale, não depende de saber, usar a respiração, o volume e a altura da voz.','C/E','E','HOMILETICA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Homilética',7,'7.8','Certo/Errado','A expressão é a forma do orador regular a emissão da voz, para não gerar a fadiga e a monotonia.','C/E','E','HOMILETICA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Homilética',7,'7.9','Certo/Errado','Expressão tem a ver com a forma de realçar uma verdade importante de seu discurso.','C/E','C','HOMILETICA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Homilética',7,'7.11','Certo/Errado','A habilidade no uso da voz é imprescindível ao bom pregador.','C/E','C','HOMILETICA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Homilética',7,'7.12','Preencher lacuna','As Palavras de ______ são aquelas que tem um papel importante, o principal, na frase.','(lacuna)','valor','HOMILETICA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Homilética',7,'7.13','Preencher lacuna','Cada ______, cada frase tem um valor.','(lacuna)','palavra','HOMILETICA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Homilética',7,'7.14','Certo/Errado','O silêncio é um dos elementos mais importantes da oratória.','C/E','C','HOMILETICA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Homilética',7,'7.15','Certo/Errado','O silencio pode ser de palavra, gestos e de atitude.','C/E','C','HOMILETICA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Homilética',7,'7.16','Certo/Errado','Um silêncio pode nem sempre corroborar.','C/E','E','HOMILETICA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Homilética',7,'7.17','Certo/Errado','Quem fala ao público deve ser capaz de dar todas as inflexões mais belas e expressivas à voz.','C/E','C','HOMILETICA.pdf L7 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.1','Certo/Errado','Nosso estilo de pregar é a maneira como fazemos, é o que funciona melhor para nós.','C/E','C','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.2','Certo/Errado','William Shakespeare, ele próprio um estilista habilidoso, fala do estilo como "aquilo que distingue ou pelo que se é distinguido".','C/E','E','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.3','Certo/Errado','O estilo foi chamado de "a assinatura do pregador".','C/E','C','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.4','Certo/Errado','O pregador não precisa ser sensível às pessoas do seu auditório.','C/E','E','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.5','Sublinhar (escolha da palavra correta)','Um dos pontos mais importantes da (História, Retórica) é a construção das frases.','História | Retórica','Retórica','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.6','Sublinhar (escolha da palavra correta)','Não se deve terminar as frases com advérbios ou preposições ou palavras de (pequena, grande) importância.','pequena | grande','pequena','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.7','Sublinhar (escolha da palavra correta)','O (verbo, sujeito) deve manter se perto do predicado.','verbo | sujeito','sujeito','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.8','Sublinhar (escolha da palavra correta)','Ouvir bons oradores ajuda no desenvolvimento de nosso (sermão, estilo).','sermão | estilo','estilo','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.9','Preencher lacuna','Pregar é uma atividade imensamente ______.','(lacuna)','criativa','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.10','Preencher lacuna','O próprio ______ é intensa e eficientemente criativo.','(lacuna)','Deus','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.11','Preencher lacuna','Existem muitas coisas, em especial em nossos maus hábitos, que ______ a criatividade.','(lacuna)','sufocam','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.12','Preencher lacuna','Uma das melhores maneiras de desenvolver a ______ é ler bons livros.','(lacuna)','imaginação','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.13','Associação de colunas','realidade dos ouvintes','A - Pessoal | B - Prática | C - Participativa | D - Objetiva | E - Contextualização','E','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.14','Associação de colunas','contato','A - Pessoal | B - Prática | C - Participativa | D - Objetiva | E - Contextualização','C','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.15','Associação de colunas','são impacientes','A - Pessoal | B - Prática | C - Participativa | D - Objetiva | E - Contextualização','D','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.16','Associação de colunas','aplicações eficientes','A - Pessoal | B - Prática | C - Participativa | D - Objetiva | E - Contextualização','B','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.17','Associação de colunas','você','A - Pessoal | B - Prática | C - Participativa | D - Objetiva | E - Contextualização','A','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.18','Certo/Errado','Spurgeon aprovava a repetição de sermões.','C/E','E','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.19','Certo/Errado','A tendência de Whitefield era a de repetir os seus sermões.','C/E','C','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.20','Certo/Errado','Interrompa a pregação de um sermão qualquer quando o mesmo deixar de tomar conta de você.','C/E','C','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.21','Certo/Errado','É perfeitamente legítimo a um pregador selecionar seu melhor sermão e pregá-lo novamente ao povo.','C/E','C','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.22','Certo/Errado','Usar sermão de outro pregador para pregar é uma questão muito polêmica.','C/E','C','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.23','Certo/Errado','Martinho Lutero achava melhor que um pregador inculto lesse um sermão bom, preparado por outro, do que proferir um discurso fraco e infrutífero, preparado por ele mesmo.','C/E','C','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.24','Certo/Errado','A igreja Metodista imprimiu um livro de homilias, para garantir a substância no ensino e na pregação.','C/E','E','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf'),
('Homilética',8,'8.25','Certo/Errado','Ao usar um sermão de gerações passadas, saiba adaptá-lo à época em que você vive e ao povo que lhe está a ouvir.','C/E','C','HOMILETICA.pdf L8 + GABARITO EXERCICIOS.pdf');

INSERT INTO public.avaliacoes_banco_questoes_licao (lesson_id, licao, formato, enunciado, opcoes, resposta_correta, fonte)
SELECT
  CASE r.materia
    WHEN 'Bibliologia' THEN (SELECT id FROM public.lessons WHERE title = 'Bibliologia')
    WHEN 'Homilética' THEN (SELECT id FROM public.lessons WHERE title = 'Homilética')
  END AS lesson_id,
  r.licao,
  CASE r.formato
    WHEN 'Certo/Errado' THEN 'CERTO_ERRADO'
    WHEN 'Múltipla escolha' THEN 'MULTIPLA_ESCOLHA'
    WHEN 'Sublinhar (escolha da palavra correta)' THEN 'MULTIPLA_ESCOLHA'
    WHEN 'Preencher lacuna' THEN 'PREENCHER_LACUNA'
    WHEN 'Associação de colunas' THEN 'ASSOCIACAO_COLUNAS'
  END AS formato,
  r.enunciado,
  CASE
    WHEN r.formato IN ('Certo/Errado', 'Preencher lacuna') THEN NULL
    ELSE to_jsonb(string_to_array(r.alternativas, ' | '))
  END AS opcoes,
  r.resposta_correta,
  r.fonte
FROM public._staging_banco_questoes_raw r;

DROP TABLE public._staging_banco_questoes_raw;
